@startuml CompleteActivityDiagram
header
generated on 3/9/2024 8:21:55 PM
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#LightBlue:string input
int number, logarithmus = 0;
:PrintLine("Logarithmus Dualis");
:PrintLine("==================");
:PrintLine();
:Print("Zahl: ");
:input = ReadLine();
:number = Convert.ToInt32(input);
while (number > 1) is (<color:green>yes)
    :number /= 2;
    :logarithmus++;
endwhile (<color:red>no)
:PrintLine();
:PrintLine($"Der Logarithmus Dualis von {number} ist {logarithmus}.");
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
