@startuml Program.Main
header
generated on 05.03.2024 11:15:19
end header
title Program.Main
start
#LightBlue:string input, fuel
double distance, consumption, consumptionPer100;
:PrintLine("Fuel Calculator");
:PrintLine("===============");
:PrintLine();
:Print("Welchen Kraftstoff tanken Sie (Diesel/Benzin)? ");
:fuel = ReadLine();
:Print("Wieviel Kilometer sind Sie gefahren?           ");
:input = ReadLine();
:distance = Convert.ToDouble(input);
:Print("Wieviel Kraftstoff haben Sie getankt?          ");
:input = ReadLine();
:consumption = Convert.ToDouble(input);
:consumptionPer100 = consumption / distance * 100;
:PrintLine();
if (fuel.ToLower() != "benzin" && fuel.ToLower() != "diesel") then (<color:green>yes)
    :PrintLine("Ungültige Kraftstoff!");
  else (<color:red>no)
      :PrintLine($"Der errechnete Durchschnittsverbrauch ist {consumptionPer100:F2} Liter pro 100 km");
      if (fuel.ToLower() == "Diesel") then (<color:green>yes)
          if (consumptionPer100 < 5.0) then (<color:green>yes)
              :PrintLine("Ihr Auto ist sparsam!");
            else (<color:red>no)
              if (consumptionPer100 <= 6.0) then (<color:green>yes)
                  :PrintLine("Ihr Auto ist im Normbereich!");
                else (<color:red>no)
                    :PrintLine("Ihr Auto verbraucht zu viel!");
              endif
          endif
        else (<color:red>no)
            if (consumptionPer100 < 6.0) then (<color:green>yes)
                :PrintLine("Ihr Auto ist sparsam!");
              else (<color:red>no)
                if (consumptionPer100 <= 7.0) then (<color:green>yes)
                    :PrintLine("Ihr Auto ist im Normbereich!");
                  else (<color:red>no)
                      :PrintLine("Ihr Auto verbraucht zu viel!");
                endif
            endif
      endif
endif
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
