@startuml Program.Main
title Program.Main
start
#LightBlue:string input
long number
long result = 1;
:PrintLine("Calculate Faculty");
:PrintLine("=================");
:PrintLine();
:Print("Please enter a number: ");
:input = ReadLine();
:number = Convert.ToInt32(input);
#LightBlue:int i = 1;
while (i <= number) is (<color:green>yes)
    :result *= i;
:i++;
endwhile (<color:red>no)
:PrintLine();
:PrintLine($"{number}! results in {result}.");
:PrintLine();
:PrintLine("Press any key to exit... ");
:ReadKey();
stop
@enduml
