@startuml Program.GetFileName
title Program.GetFileName
participant "GetFileName" as GetFileName #LightYellow
participant "Console.Write(a0)" as Console_Write_a0 #LightGreen
participant "File.Exists(a0)" as File_Exists_a0 #LightGreen
participant "string.IsNullOrEmpty(a0)" as string_IsNullOrEmpty_a0 #LightGreen
autonumber
loop#LightCoral string.IsNullOrEmpty(result)
    alt#LightBlue counter++ == 0
        GetFileName -[#grey]> Console_Write_a0 : ("Dateiname ohne Endung: ")
        else
            GetFileName -[#grey]> Console_Write_a0 : (@"Dateiname ohne Endung <im Anwendungsverzeichnis \bin\debug>: ")
    end
    alt#LightBlue File.Exists(input)
        GetFileName -[#grey]> File_Exists_a0 : (input)
    end
    GetFileName -[#grey]> string_IsNullOrEmpty_a0 : (result)
    string_IsNullOrEmpty_a0 -[#blue]-> GetFileName : result
end
@enduml
