@startuml Program.Main
title Program.Main
start
:PrintLine("***************************************************");
:PrintLine("* ASCII - Tabelle                                 *");
:PrintLine("***************************************************");
:PrintLine();
:int idx = FIRST_ASCII;
while (idx <= LAST_ASCII) is (yes)
    :PrintLine(output);
:idx++;
endwhile (no)
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
@enduml
