@startuml Program.Main
header
generated on 05.03.2024 11:15:20
end header
title Program.Main
start
#LightBlue:string inputText, searchText
int index = -1;
:PrintLine("String Search!");
:PrintLine("==============");
:PrintLine();
:Print("Eingabetext....: ");
:inputText = ReadLine();
if (inputText != "") then (<color:green>yes)
    :Print("Suchtext.......: ");
    :searchText = ReadLine();
    #LightBlue:int i = 0;
    while (index == -1 && searchText.Length > 0 && i <= inputText.Length - searchText.Length) is (<color:green>yes)
        #LightBlue:int j = 0;
        #LightBlue:bool check = true;
        while (check && j < searchText.Length) is (<color:green>yes)
            :check = char.ToLower(inputText[i + j]) == char.ToLower(searchText[j++]);
        endwhile (<color:red>no)
        :index = check ? i : index;
    :i++;
    endwhile (<color:red>no)
    if (index >= 0) then (<color:green>yes)
        :PrintLine();
        :PrintLine($"Der Suchtext wurde an der Position {index} gefunden.");
      else (<color:red>no)
          :PrintLine();
          :PrintLine($"Der Suchtext wurde nicht gefunden.");
    endif
    :Print("Weiter mit Enter...");
    :ReadLine();
endif
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
