@startuml CompleteActivityDiagram
title CompleteActivityDiagram
start
note right:  Program.Main
#LightBlue:string input
int number;
:PrintLine("StarSquare");
:PrintLine("==========");
:PrintLine();
:Print("Geben Sie eine Ganzzahl ein: ");
:input = ReadLine();
:number = Convert.ToInt32(input);
:PrintLine();
:int i = 0;
while (i < number) is (<color:green>yes)
    :int j = 0;
    while (j < number) is (<color:green>yes)
        :Print("* ");
    :j++;
    endwhile (<color:red>no)
    :PrintLine();
:i++;
endwhile (<color:red>no)
stop
@enduml
