@startuml CompleteActivityDiagram
header
generated on 12.03.2024 22:57:10
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#Lavender:Params(string[] args);
#LightBlue:string input
int number;
:PrintLine("StarSquare");
:PrintLine("==========");
:PrintLine();
:Print("Geben Sie eine Ganzzahl ein: ");
:input = ReadLine();
:number = Convert.ToInt32(input);
:PrintLine();
#LightBlue:int i = 0;
while (i < number) is (<color:green>yes)
    #LightBlue:int j = 0;
    while (j < number) is (<color:green>yes)
        :Print("* ");
    :j++;
    endwhile (<color:red>no)
    :PrintLine();
:i++;
endwhile (<color:red>no)
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
