@startuml Program.Main
title Program.Main
start
#LightGreen:Params(string[] args);
#WhiteSmoke:PrintLine("PlantUML-Creator");
#LightSkyBlue:var slnPath = GetCurrentSolutionPath()\nvar files = GetSourceCodeFiles(slnPath, ["*.cs"]);
:iterator = files.GetIterator();
while (iterator.MoveNext()) is (<color:green>yes)
:file = iterator.Current();
            #LightSkyBlue:var sourcePath = Path.GetDirectoryName(file);
            #LightSkyBlue:var diagramsPath = Path.Combine(sourcePath!, "Diagrams");
            #LightSkyBlue:var source = File.ReadAllText(file!);
            #WhiteSmoke:UMLCreator.CreateActivityDiagram(diagramsPath, source);
endwhile (<color:red>no)
stop
@enduml
