@startuml Program.GetCurrentSolutionPath
title Program.GetCurrentSolutionPath
start
#LightBlue:int endPos = AppContext.BaseDirectory
                                   .IndexOf($"{nameof(PlantUML)}", StringComparison.CurrentCultureIgnoreCase)
var result = AppContext.BaseDirectory[..endPos];
while (result.EndsWith(Path.DirectorySeparatorChar)) is (<color:green>yes)
    :result = result[0..^1];
endwhile (<color:red>no)
stop
@enduml
