@startuml Program.GetSourceCodeFiles
header
generated on 3/9/2024 8:21:55 PM
end header
title Program.GetSourceCodeFiles
start
#LightBlue:var result = new List<string>()
var ignoreFolders = new string[] { $"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}", $"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}" };
:iterator = searchPatterns.GetIterator();
while (iterator.MoveNext()) is (<color:green>yes)
:current = iterator.Current();
      :result.AddRange(Directory.GetFiles(path, current, SearchOption.AllDirectories)
                      .Where(f => ignoreFolders.Any(e => f.Contains(e)) == false)
                      .OrderBy(i => i));
endwhile (<color:red>no)
#Lavender:return result;
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
