@startuml Program.GetCurrentSolutionPath
title Program.GetCurrentSolutionPath
start
#LightSkyBlue:int endPos = AppContext.BaseDirectory
                                   .IndexOf($"{nameof(PlantUML)}", StringComparison.CurrentCultureIgnoreCase)\nvar result = AppContext.BaseDirectory[..endPos];
while (result.EndsWith(Path.DirectorySeparatorChar)) is (<color:green>yes)
        #WhiteSmoke:result = result[0..^1];
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
