@startuml StringExtensions.SetIndent
header
generated on 05.03.2024 11:15:20
end header
title StringExtensions.SetIndent
start
if (lines != null) then (<color:green>yes)
    #LightBlue:int i = 0;
    while (i < lines.Length) is (<color:green>yes)
        :lines[i] = lines[i].SetIndent(count);
    :i++;
    endwhile (<color:red>no)
endif
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
