@startuml UMLCreator.CreateActivityDiagram
title UMLCreator.CreateActivityDiagram
start
#LightBlue:var diagramData = new List<string>()
var statements = methodNode?.Body?.Statements;
:iterator = statements!.GetIterator();
while (iterator.MoveNext()) is (<color:green>yes)
:current = iterator.Current();
      :AnalysisStatement(current, diagramData, 0);
endwhile (<color:red>no)
#Lavender:return diagramData;
stop
@enduml
