@startuml UMLCreator.CreateActivityDiagram
header
generated on 3/9/2024 8:21:55 PM
end header
title UMLCreator.CreateActivityDiagram
start
#LightBlue:var diagramData = new List<string>()
var statements = methodNode?.Body?.Statements;
:iterator = statements!.GetIterator();
while (iterator.MoveNext()) is (<color:green>yes)
:current = iterator.Current();
      :AnalysisStatement(current, diagramData, 0);
endwhile (<color:red>no)
#Lavender:return diagramData;
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
