@startuml StringExtensions
title StringExtensions
{static} class StringExtensions #GhostWhite {
+ {static} string Indent = "  "
---
---
+ {static} string SetIndent(string text, int count)
+ {static} string[] SetIndent(string[] lines, int count)
}
@enduml
