@startuml UMLCreator
title UMLCreator
 class UMLCreator #GhostWhite {
---
---
+ {static} void CreateActivityDiagram(string path, string source)
+ {static} List<string> CreateActivityDiagram(MethodDeclarationSyntax methodNode)
+ {static} void AnalysisStatement(SyntaxNode syntaxNode, List<string> diagramData, int level)
}
@enduml
