@startuml Program.Main
title Program.Main
start
:PrintLine("PlantUML-Creator");
:var slnPath = GetCurrentSolutionPath();
:var files = GetSourceCodeFiles(slnPath, ["*.cs"]);
:iterator = files.GetIterator();
while (iterator.MoveNext()) is (yes)
:current = iterator.Current();
      :var sourcePath = Path.GetDirectoryName(current);
      :var diagramsPath = Path.Combine(sourcePath!, "Diagrams");
      :var source = File.ReadAllText(current!);
      :UMLCreator.CreateActivityDiagram(diagramsPath, source);
endwhile (no)
stop
@enduml
