@startuml Program.GetCurrentSolutionPath
title Program.GetCurrentSolutionPath
participant "GetCurrentSolutionPath" as GetCurrentSolutionPath #LightYellow
participant "AppContext.BaseDirectory.IndexOf(a0,a1)" as AppContext_BaseDirectory_IndexOf_a0_a1 #LightGreen
participant "result.EndsWith(a0)" as result_EndsWith_a0 #LightGreen
autonumber
GetCurrentSolutionPath -> AppContext_BaseDirectory_IndexOf_a0_a1 : ($"{nameof(PlantUML)}", StringComparison.CurrentCultureIgnoreCase)
AppContext_BaseDirectory_IndexOf_a0_a1 --> GetCurrentSolutionPath : endPos
loop result.EndsWith(Path.DirectorySeparatorChar)
    GetCurrentSolutionPath -> result_EndsWith_a0 : (Path.DirectorySeparatorChar)
end
@enduml
