@startuml Program.CreateBackup
title Program.CreateBackup
participant "File.Exists(a0)" as File_Exists_a0 #LightGreen
participant "File.Copy(a0,a1)" as File_Copy_a0_a1 #LightGreen
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
autonumber
loop#LightCoral File.Exists(backupFileName)
    CreateBackup_p0 -[#grey]> File_Exists_a0 : (backupFileName)
end
alt#LightBlue File.Exists(fileName)
    CreateBackup_p0 -[#grey]> File_Exists_a0 : (fileName)
    CreateBackup_p0 -[#grey]> File_Copy_a0_a1 : (fileName, backupFileName)
    CreateBackup_p0 -[#grey]> Console_WriteLine_a0 : ($"Die Sicherungskopie '{backupFileName}' wurde erstellt.")
    else
        CreateBackup_p0 -[#grey]> Console_WriteLine_a0 : ($"Die Datei '{fileName}' existiert nicht!")
end
@enduml
