@startuml Program.Main
title Program.Main
participant "Main(string[]args)" as Main_p0 #LightYellow
participant "File.ReadAllText(a0,a1)" as File_ReadAllText_a0_a1 #LightGreen
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
participant "GetFileName()" as GetFileName #LightGreen
participant "CreateBackup(a0)" as CreateBackup_a0 #LightGreen
participant "PerformOperation(a0)" as PerformOperation_a0 #LightGreen
participant "Thread.Sleep(a0)" as Thread_Sleep_a0 #LightGreen
autonumber
Main_p0 -[#grey]> File_ReadAllText_a0_a1 : (LOGO_FILE, Encoding.Default)
File_ReadAllText_a0_a1 -[#blue]-> Main_p0 : logo
Main_p0 -[#grey]> Console_WriteLine_a0 : (logo)
Main_p0 -[#grey]> GetFileName
GetFileName -[#blue]-> Main_p0 : fileName
Main_p0 -[#grey]> CreateBackup_a0 : (fileName)
loop#LightCoral finished == false
    Main_p0 -[#grey]> PerformOperation_a0 : (ref fileName)
    PerformOperation_a0 -[#blue]-> Main_p0 : finished
end
Main_p0 -[#grey]> Console_WriteLine_a0 : ("Vielen Dank, dass ich Dir helfen durfte!")
Main_p0 -[#grey]> Thread_Sleep_a0 : (3000)
@enduml
