@startuml Program.Main
title Program.Main
participant "Main(string[]args)" as Main_p0 #LightYellow
participant "File.ReadAllText(a0,a1)" as File_ReadAllText_a0_a1 #LightGreen
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
participant "GetFileName()" as GetFileName #LightGreen
participant "CreateBackup(a0)" as CreateBackup_a0 #LightGreen
participant "PerformOperation(a0)" as PerformOperation_a0 #LightGreen
participant "Thread.Sleep(a0)" as Thread_Sleep_a0 #LightGreen
autonumber
Main_p0 -> File_ReadAllText_a0_a1 : (LOGO_FILE, Encoding.Default)
File_ReadAllText_a0_a1 --> Main_p0 : logo
Main_p0 -> Console_WriteLine_a0 : (logo)
Main_p0 -> GetFileName
GetFileName --> Main_p0 : fileName
Main_p0 -> CreateBackup_a0 : (fileName)
loop finished == false
    Main_p0 -> PerformOperation_a0 : (ref fileName)
    PerformOperation_a0 --> Main_p0 : finished
end
Main_p0 -> Console_WriteLine_a0 : ("Vielen Dank, dass ich Dir helfen durfte!")
Main_p0 -> Thread_Sleep_a0 : (3000)
@enduml
