@startuml Program.Main
title Program.Main
start
:PrintLine("Number Puzzel");
:PrintLine("=============");
:PrintLine();
:PrintLine("Solve:");
:PrintLine("  a + bc = 2024");
:PrintLine("  ab + c = 2023");
:PrintLine();
:a = 0;
:b = 0;
:c = 0;
while (solved == false && a < A_plus_B_x_C) is (yes)
    :a++;
    :b = 0;
    while (solved == false && b < A_plus_B_x_C) is (yes)
        :b++;
        :c = 0;
        while (solved == false && c < A_plus_B_x_C) is (yes)
            :c++;
            :equation_1 = a + (b * c);
            :equation_2 = (a * b) + c;
            :solved = equation_1 == A_plus_B_x_C && equation_2 == A_x_B_plus_C;
        endwhile (no)
    endwhile (no)
endwhile (no)
if (solved) then (yes)
    :PrintLine($"The solution: a == {a}, b == {b} and c == {c}");
  else (no)
      :PrintLine("No solution found!");
endif
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
@enduml
