@startuml CompleteActivityDiagram
header
generated on 3/9/2024 8:21:55 PM
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#LightBlue:int PARAMS_PRODUCT = 32118
int MAX_AGE = 100
int children
int age
int shipLength;
:PrintLine("Käpt'n Hooks Rätsel");
:PrintLine("===================");
:PrintLine();
:children = 4;
:age = children + 1;
:shipLength = 1;
while (children * age * shipLength != PARAMS_PRODUCT && children < MAX_AGE) is (<color:green>yes)
    :children++;
    :age = children;
    repeat
        :age++;
        :shipLength = PARAMS_PRODUCT / (children * age);
    repeat while (children * age * shipLength != PARAMS_PRODUCT && age < MAX_AGE) is (<color:green>yes)
endwhile (<color:red>no)
if (children * age * shipLength == PARAMS_PRODUCT) then (<color:green>yes)
    :PrintLine();
    :PrintLine($"Die Lösung des Rätsels:");
    :PrintLine($"Anzahl der Kinder:     {children}");
    :PrintLine($"Alter des Kapitains:   {age}");
    :PrintLine($"Schiffslänge in Meter: {shipLength}");
  else (<color:red>no)
      :PrintLine();
      :PrintLine($"Es gibt keine Lösung für das Produkt der Parameter von {PARAMS_PRODUCT}!");
endif
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
