@startuml CompleteActivityDiagram
header
generated on 09/04/2024 14:46:35
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#LightGreen:Params(string[] args);
#LightSkyBlue:int PARAMS_PRODUCT = 32118\nint MAX_AGE = 100\nint children\nint age\nint shipLength;
#WhiteSmoke:PrintLine("Käpt'n Hooks Rätsel");
#WhiteSmoke:PrintLine("===================");
#WhiteSmoke:PrintLine();
#WhiteSmoke:children = 4;
#WhiteSmoke:age = children + 1;
#WhiteSmoke:shipLength = 1;
while (children * age * shipLength != PARAMS_PRODUCT && children < MAX_AGE) is (<color:green>yes)
        #WhiteSmoke:children++;
        #WhiteSmoke:age = children;
        repeat
                #WhiteSmoke:age++;
                #WhiteSmoke:shipLength = PARAMS_PRODUCT / (children * age);
        repeat while (children * age * shipLength != PARAMS_PRODUCT && age < MAX_AGE) is (<color:green>yes)
endwhile (<color:red>no)
if (children * age * shipLength == PARAMS_PRODUCT) then (<color:green>yes)
        #WhiteSmoke:PrintLine();
        #WhiteSmoke:PrintLine($"Die Lösung des Rätsels:");
        #WhiteSmoke:PrintLine($"Anzahl der Kinder:     {children}");
        #WhiteSmoke:PrintLine($"Alter des Kapitains:   {age}");
        #WhiteSmoke:PrintLine($"Schiffslänge in Meter: {shipLength}");
    else (<color:red>no)
            #WhiteSmoke:PrintLine();
            #WhiteSmoke:PrintLine($"Es gibt keine Lösung für das Produkt der Parameter von {PARAMS_PRODUCT}!");
endif
#WhiteSmoke:PrintLine();
#WhiteSmoke:PrintLine("Press any key to exit: ");
#WhiteSmoke:ReadKey();
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
