@startuml Program.CreateRandomField
title Program.CreateRandomField
start
#LightBlue:int count = 0
int[,] field = new int[Math.Max(rows, 0), Math.Max(cols, 0)];
:occupancy = Math.Min(occupancy, rows * cols);
while (count < occupancy) is (<color:green>yes)
    #LightBlue:int r = Random.Shared.Next(0, rows);
    #LightBlue:int c = Random.Shared.Next(0, cols);
    if (field[r, c] == 0) then (<color:green>yes)
        :field[r, c] = 1;
        :count++;
    endif
endwhile (<color:red>no)
#Lavender:return field;
stop
@enduml
