@startuml Program.PrintField
title Program.PrintField
start
:Console.Clear();
:Console.ForegroundColor = ConsoleColor.Yellow;
#LightBlue:int r = 0;
while (r < field.GetLength(0)) is (<color:green>yes)
    #LightBlue:int c = 0;
    while (c < field.GetLength(1)) is (<color:green>yes)
        #LightBlue:char sign = field[r, c] == 0 ? ' ' : '*';
        :Print($" {sign} ");
    :c++;
    endwhile (<color:red>no)
    :PrintLine();
:r++;
endwhile (<color:red>no)
stop
@enduml
