@startuml Program.ReadFieldFromCsvFile
title Program.ReadFieldFromCsvFile
start
#LightBlue:bool isDefined = false
int[,] result = new int[0, 0];
if (File.Exists(filePath)) then (<color:green>yes)
    #LightBlue:string[] lines = File.ReadAllLines(filePath);
    #LightBlue:int r = 0;
    while (r < lines.Length) is (<color:green>yes)
        #LightBlue:string[] values = lines[r].Split(';');
        if (isDefined == false) then (<color:green>yes)
            :result = new int[lines.Length, values.Length];
            :isDefined = true;
        endif
        #LightBlue:int c = 0;
        while (c < values.Length) is (<color:green>yes)
            :result[r, c] = int.Parse(values[c]);
        :c++;
        endwhile (<color:red>no)
    :r++;
    endwhile (<color:red>no)
endif
#Lavender:return result;
stop
@enduml
