@startuml Program.CreateNextGeneration
title Program.CreateNextGeneration
participant "CreateNextGeneration(int[,] currentField)" as CreateNextGeneration_p0 #LightYellow
participant "currentField.GetLength(a0)" as currentField.GetLength_a0 #LightGreen
participant "GetLivingNeighbors(a0, a1, a2)" as GetLivingNeighbors_a0_a1_a2 #LightGreen
autonumber
CreateNextGeneration_p0 -> currentField.GetLength_a0 : (0)
CreateNextGeneration_p0 -> currentField.GetLength_a0 : (1)
@enduml
