@startuml Program.ReadFieldFromCsvFile
title Program.ReadFieldFromCsvFile
participant "ReadFieldFromCsvFile(stringfilePath)" as ReadFieldFromCsvFile_p0 #LightYellow
participant "File.Exists(a0)" as File_Exists_a0 #LightGreen
participant "File.ReadAllLines(a0)" as File_ReadAllLines_a0 #LightGreen
participant "lines[r].Split(a0)" as lines_r_Split_a0 #LightGreen
participant "int.Parse(a0)" as int_Parse_a0 #LightGreen
autonumber
alt File.Exists(filePath)
    ReadFieldFromCsvFile_p0 -> File_Exists_a0 : (filePath)
    ReadFieldFromCsvFile_p0 -> File_ReadAllLines_a0 : (filePath)
    File_ReadAllLines_a0 --> ReadFieldFromCsvFile_p0 : lines
    loop r < lines.Length
        ReadFieldFromCsvFile_p0 -> lines_r_Split_a0 : (';')
        lines_r_Split_a0 --> ReadFieldFromCsvFile_p0 : values
        loop c < values.Length
            ReadFieldFromCsvFile_p0 -> int_Parse_a0 : (values[c])
            int_Parse_a0 --> ReadFieldFromCsvFile_p0 : result[r, c]
        end
    end
end
@enduml
