@startuml Program.GetLivingNeighbors
title Program.GetLivingNeighbors
participant "GetLivingNeighbors(int[,] field,int row,int col)" as GetLivingNeighbors_p0_p1_p2 #LightYellow
participant "field.GetLength(a0)" as field.GetLength_a0 #LightGreen
autonumber
@enduml
