@startuml Program.SumCellValues
title Program.SumCellValues
participant "SumCellValues(int[,]field)" as SumCellValues_p0 #LightYellow
participant "field.GetLength(a0)" as field_GetLength_a0 #LightGreen
autonumber
SumCellValues_p0 -[#grey]> field_GetLength_a0 : (0)
field_GetLength_a0 -[#blue]-> SumCellValues_p0 : result
SumCellValues_p0 -[#grey]> field_GetLength_a0 : (1)
field_GetLength_a0 -[#blue]-> SumCellValues_p0 : result
@enduml
