@startuml Program.Main
header
generated on 3/9/2024 8:21:55 PM
end header
title Program.Main
start
#LightBlue:int FIRST_ASCII = 32
int LAST_ASCII = 127;
:PrintLine("***************************************************");
:PrintLine("* ASCII - Tabelle                                 *");
:PrintLine("***************************************************");
:PrintLine();
#LightBlue:int idx = FIRST_ASCII;
while (idx <= LAST_ASCII) is (<color:green>yes)
    #LightBlue:char printChar = Convert.ToChar(FIRST_ASCII + idx);
    #LightBlue:string output = $"Zeichen: {printChar} Code: {idx,4} (dec) {idx.ToString("X4")} (hex)";
    :PrintLine(output);
:idx++;
endwhile (<color:red>no)
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
