@startuml Program.Main
title Program.Main
start
:int FIRST_ASCII = 32;
:int LAST_ASCII = 127;
:PrintLine("***************************************************");
:PrintLine("* ASCII - Tabelle                                 *");
:PrintLine("***************************************************");
:PrintLine();
:int idx = FIRST_ASCII;
while (idx <= LAST_ASCII) is (yes)
    :char printChar = Convert.ToChar(FIRST_ASCII + idx);
    :string output = $"Zeichen: {printChar} Code: {idx,4} (dec) {idx.ToString("X4")} (hex)";
    :PrintLine(output);
:idx++;
endwhile (no)
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
@enduml
