@startuml Program.Main
title Program.Main
participant "Main(string[]args)" as Main_p0 #LightYellow
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
participant "Console.WriteLine()" as Console_WriteLine #LightGreen
participant "Convert.ToChar(a0)" as Convert_ToChar_a0 #LightGreen
participant "Console.ReadKey()" as Console_ReadKey #LightGreen
autonumber
Main_p0 -> Console_WriteLine_a0 : ("***************************************************")
Main_p0 -> Console_WriteLine_a0 : ("* ASCII - Tabelle                                 *")
Main_p0 -> Console_WriteLine_a0 : ("***************************************************")
Main_p0 -> Console_WriteLine
loop idx <= LAST_ASCII
    Main_p0 -> Convert_ToChar_a0 : (FIRST_ASCII + idx)
    Convert_ToChar_a0 --> Main_p0 : printChar
    Main_p0 -> Console_WriteLine_a0 : (output)
end
Main_p0 -> Console_WriteLine
Main_p0 -> Console_WriteLine_a0 : ("Press any key to exit: ")
Main_p0 -> Console_ReadKey
@enduml
