@startuml Program.Main
title Program.Main
start
#LightGreen:Params(string[] args);
#WhiteSmoke:PrintLine("Count Different Digits");
#WhiteSmoke:PrintLine("======================");
#WhiteSmoke:PrintLine();
#LightSkyBlue:int[] digits = ReadDigits()\nstring output = string.Join("", digits)\nstring uniqueDigits = GetUniqueDigitsString(digits);
#WhiteSmoke:PrintLine($"Eingegebene Ziffern im Array: {output}");
#WhiteSmoke:PrintLine($"Eindeutige Ziffern im Array : {uniqueDigits}");
#WhiteSmoke:PrintLine();
#WhiteSmoke:PrintLine("Beenden mit Eingabetaste... ");
#WhiteSmoke:ReadLine();
stop
@enduml
