@startuml Program.GetUniqueDigitsString
title Program.GetUniqueDigitsString
start
#LightGreen:Params(int[] digits);
#LightSkyBlue:string result = string.Empty;
#LightSkyBlue:int i = 0;
while (i < digits.Length) is (<color:green>yes)
        if (result.Contains(digits[i].ToString()) == false) then (<color:green>yes)
                #WhiteSmoke:result += digits[i].ToString();
        endif
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
