@startuml Program.ReadDigits
title Program.ReadDigits
start
#LightSkyBlue:int MAX_NUMBERS = 10\nint[] result = new int[MAX_NUMBERS]\nint count = 1, index = 0\nstring input = string.Empty;
while (count <= MAX_NUMBERS) is (<color:green>yes)
        #WhiteSmoke:Print($"{count, 2}. Ziffer [0-9] eingeben: ");
        #WhiteSmoke:input = ReadLine();
        if (int.TryParse(input, out result[index])) then (<color:green>yes)
                if (result[index] < 0 || result[index] > 9) then (<color:green>yes)
                        #WhiteSmoke:PrintLine("Fehleingabe, Ziffer muss zwischen 0 und 9 liegen!");
                    else (<color:red>no)
                            #WhiteSmoke:count++;
                            #WhiteSmoke:index++;
                endif
            else (<color:red>no)
                    #WhiteSmoke:PrintLine("Fehleingabe, es muss eine Ziffer zwischen 0 und 9 sein!");
        endif
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
