@startuml CompleteActivityDiagram
header
generated on 09.04.2024 22:12:00
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#LightGreen:Params(string[] args);
#WhiteSmoke:PrintLine("Count Different Digits");
#WhiteSmoke:PrintLine("======================");
#WhiteSmoke:PrintLine();
#LightSkyBlue:int[] digits = ReadDigits()\nstring output = string.Join("", digits)\nstring uniqueDigits = GetUniqueDigitsString(digits);
#WhiteSmoke:PrintLine($"Eingegebene Ziffern im Array: {output}");
#WhiteSmoke:PrintLine($"Eindeutige Ziffern im Array : {uniqueDigits}");
#WhiteSmoke:PrintLine();
#WhiteSmoke:PrintLine("Beenden mit Eingabetaste... ");
#WhiteSmoke:ReadLine();
stop
start
note right:  Program.ReadDigits
#LightSkyBlue:int MAX_NUMBERS = 10\nint[] result = new int[MAX_NUMBERS]\nint count = 1, index = 0\nstring input = string.Empty;
while (count <= MAX_NUMBERS) is (<color:green>yes)
        #WhiteSmoke:Print($"{count, 2}. Ziffer [0-9] eingeben: ");
        #WhiteSmoke:input = ReadLine();
        if (int.TryParse(input, out result[index])) then (<color:green>yes)
                if (result[index] < 0 || result[index] > 9) then (<color:green>yes)
                        #WhiteSmoke:PrintLine("Fehleingabe, Ziffer muss zwischen 0 und 9 liegen!");
                    else (<color:red>no)
                            #WhiteSmoke:count++;
                            #WhiteSmoke:index++;
                endif
            else (<color:red>no)
                    #WhiteSmoke:PrintLine("Fehleingabe, es muss eine Ziffer zwischen 0 und 9 sein!");
        endif
endwhile (<color:red>no)
#Lavender:return result;
stop
start
note right:  Program.GetUniqueDigitsString
#LightGreen:Params(int[] digits);
#LightSkyBlue:string result = string.Empty;
#LightSkyBlue:int i = 0;
while (i < digits.Length) is (<color:green>yes)
        if (result.Contains(digits[i].ToString()) == false) then (<color:green>yes)
                #WhiteSmoke:result += digits[i].ToString();
        endif
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
