@startuml Program.ReadDigits
title Program.ReadDigits
start
:int MAX_NUMBERS = 10;
:int[] result = new int[MAX_NUMBERS];
:int count = 1, index = 0;
:string input = string.Empty;
while (count <= MAX_NUMBERS) is (yes)
    :Print($"{count, 2}. Ziffer [0-9] eingeben: ");
    :input = ReadLine();
    if (int.TryParse(input, out result[index])) then (yes)
        if (result[index] < 0 || result[index] > 9) then (yes)
            :PrintLine("Fehleingabe, Ziffer muss zwischen 0 und 9 liegen!");
          else (no)
              :count++;
              :index++;
        endif
      else (no)
          :PrintLine("Fehleingabe, es muss eine Ziffer zwischen 0 und 9 sein!");
    endif
endwhile (no)
stop
@enduml
