@startuml Program.Main
title Program.Main
participant "Main(string[]args)" as Main_p0 #LightYellow
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
participant "Console.WriteLine()" as Console_WriteLine #LightGreen
participant "ReadDigits()" as ReadDigits #LightGreen
participant "string.Join(a0,a1)" as string_Join_a0_a1 #LightGreen
participant "GetUniqueDigitsString(a0)" as GetUniqueDigitsString_a0 #LightGreen
participant "Console.ReadLine()" as Console_ReadLine #LightGreen
autonumber
Main_p0 -[#grey]> Console_WriteLine_a0 : ("Count Different Digits")
Main_p0 -[#grey]> Console_WriteLine_a0 : ("======================")
Main_p0 -[#grey]> Console_WriteLine
Main_p0 -[#grey]> ReadDigits
ReadDigits -[#blue]-> Main_p0 : digits
Main_p0 -[#grey]> string_Join_a0_a1 : ("", digits)
string_Join_a0_a1 -[#blue]-> Main_p0 : output
Main_p0 -[#grey]> GetUniqueDigitsString_a0 : (digits)
GetUniqueDigitsString_a0 -[#blue]-> Main_p0 : uniqueDigits
Main_p0 -[#grey]> Console_WriteLine_a0 : ($"Eingegebene Ziffern im Array: {output}")
Main_p0 -[#grey]> Console_WriteLine_a0 : ($"Eindeutige Ziffern im Array : {uniqueDigits}")
Main_p0 -[#grey]> Console_WriteLine
Main_p0 -[#grey]> Console_WriteLine_a0 : ("Beenden mit Eingabetaste... ")
Main_p0 -[#grey]> Console_ReadLine
@enduml
