@startuml Program.Main
title Program.Main
start
:PrintLine("String Search!");
:PrintLine("==============");
:PrintLine();
:Print("Eingabetext....: ");
:inputText = ReadLine();
if (inputText != "") then (yes)
    :Print("Suchtext.......: ");
    :searchText = ReadLine();
    :int i = 0;
    while (index == -1 && searchText.Length > 0 && i <= inputText.Length - searchText.Length) is (yes)
        while (check && j < searchText.Length) is (yes)
            :check = char.ToLower(inputText[i + j]) == char.ToLower(searchText[j++]);
        endwhile (no)
        :index = check ? i : index;
    :i++;
    endwhile (no)
    if (index >= 0) then (yes)
        :PrintLine();
        :PrintLine($"Der Suchtext wurde an der Position {index} gefunden.");
      else (no)
          :PrintLine();
          :PrintLine($"Der Suchtext wurde nicht gefunden.");
    endif
    :Print("Weiter mit Enter...");
    :ReadLine();
endif
stop
@enduml
