@startuml StringExtensions.SetIndent
title StringExtensions.SetIndent
start
if (lines != null) then (yes)
    :int i = 0;
    while (i < lines.Length) is (yes)
        :lines[i] = lines[i].SetIndent(count);
    :i++;
    endwhile (no)
endif
stop
@enduml
