@startuml CompleteActivityDiagram
header
generated on 12.03.2024 22:57:03
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#Lavender:Params(string[] args);
#LightBlue:string input
int counter = 0
int guessNumber
int randomNumber = Random.Shared.Next(1, 101);
:PrintLine("Zahlenraten");
:PrintLine("===========");
:PrintLine();
:PrintLine("Ich habe mir eine Zahl zwischen 1 und 100 ausgedacht. Kannst du sie erraten?");
repeat
    :Print($"{++counter}. Versuch: ");
    :input = ReadLine();
    :guessNumber = Convert.ToInt32(input);
    if (guessNumber < randomNumber) then (<color:green>yes)
        :Print("Die gesuchte Zahl ist größer, ");
      else (<color:red>no)
        if (guessNumber > randomNumber) then (<color:green>yes)
            :Print("Die gesuchte Zahl ist kleiner, ");
        endif
    endif
repeat while (guessNumber != randomNumber) is (<color:green>yes)
if (counter > 1 && counter <= 5) then (<color:green>yes)
    :PrintLine("Tolle Leistung!");
  else (<color:red>no)
    if (counter > 5 && counter <= 10) then (<color:green>yes)
        :PrintLine("Schon ganz gut!");
      else (<color:red>no)
          :PrintLine("Endlich geschafft!");
    endif
endif
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
