@startuml Program.AddLeadingCharacters
header
generated on 3/9/2024 8:21:55 PM
end header
title Program.AddLeadingCharacters
start
#LightBlue:string result = number
int length = number.Length + count;
while (result.Length < length) is (<color:green>yes)
    :result = chr + result;
endwhile (<color:red>no)
#Lavender:return result;
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
