@startuml Program.ReadBigInteger
header
generated on 08.03.2024 08:27:27
end header
title Program.ReadBigInteger
start
#LightBlue:string result
bool validInput;
repeat
    :Print(prompt);
    :result = ReadLine();
    :validInput = IsBigNumber(result);
    if (validInput == false) then (<color:green>yes)
        :PrintLine("Ungültige Eingabe!");
    endif
repeat while (validInput == false) is (<color:green>yes)
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
