@startuml Program.Main
header
generated on 08.03.2024 08:27:27
end header
title Program.Main
start
#LightBlue:string number1, number2, result;
:PrintLine("Addieren von sehr großen Zahlen (Integer)");
:PrintLine("=========================================");
:number1 = ReadBigInteger("Geben Sie die erste Zahl ein: ");
:number2 = ReadBigInteger("Geben Sie die zweite Zahl ein:");
:result = AddBigInteger(number1, number2);
:PrintLine("Summer der beiden Zahlen:");
:PrintLine($"{result}");
:PrintLine();
:PrintLine("Beenden mit Eingabetaste... ");
:ReadLine();
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
