@startuml Program.ReadBigInteger
header
generated on 3/9/2024 8:21:55 PM
end header
title Program.ReadBigInteger
start
#LightBlue:string result
bool validInput;
repeat
    :Print(prompt);
    :result = ReadLine();
    :validInput = IsBigNumber(result);
    if (validInput == false) then (<color:green>yes)
        :PrintLine("Ungültige Eingabe!");
    endif
repeat while (validInput == false) is (<color:green>yes)
#Lavender:return result;
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
