@startuml Program.AddLeadingCharacters
title Program.AddLeadingCharacters
start
#LightGreen:Params(string number,char chr,int count);
#LightSkyBlue:string result = number\nint length = number.Length + count;
while (result.Length < length) is (<color:green>yes)
        #WhiteSmoke:result = chr + result;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
