@startuml CompleteActivityDiagram
header
generated on 03.04.2024 13:49:57
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#LightGreen:Params(string[] args);
#LightSkyBlue:string number1, number2, result;
#WhiteSmoke:PrintLine("Addieren von sehr großen Zahlen (Integer)");
#WhiteSmoke:PrintLine("=========================================");
#WhiteSmoke:number1 = ReadBigInteger("Geben Sie die erste Zahl ein: ");
#WhiteSmoke:number2 = ReadBigInteger("Geben Sie die zweite Zahl ein:");
#WhiteSmoke:result = AddBigInteger(number1, number2);
#WhiteSmoke:PrintLine("Summer der beiden Zahlen:");
#WhiteSmoke:PrintLine($"{result}");
#WhiteSmoke:PrintLine();
#WhiteSmoke:PrintLine("Beenden mit Eingabetaste... ");
#WhiteSmoke:ReadLine();
stop
start
note right:  Program.AddBigInteger
#LightGreen:Params(string number1,string number2);
#LightSkyBlue:string result = string.Empty
int maxNumber = Math.Max(number1.Length, number2.Length) + 1
bool carry = false;
#WhiteSmoke:number1 = AddLeadingCharacters(number1, '0', maxNumber - number1.Length);
#WhiteSmoke:number2 = AddLeadingCharacters(number2, '0', maxNumber - number2.Length);
#LightSkyBlue:int i = number1.Length - 1;
while (i >= 0) is (<color:green>yes)
        #LightSkyBlue:int sum = number1[i] - '0' + number2[i] - '0' + (carry ? 1 : 0);
        if (sum < 10) then (<color:green>yes)
                #WhiteSmoke:result = sum.ToString() + result;
                #WhiteSmoke:carry = false;
            else (<color:red>no)
                    #WhiteSmoke:result = (sum % 10).ToString() + result;
                    #WhiteSmoke:carry = true;
        endif
:i--;
endwhile (<color:red>no)
#Lavender:return result;
stop
start
note right:  Program.AddLeadingCharacters
#LightGreen:Params(string number,char chr,int count);
#LightSkyBlue:string result = number
int length = number.Length + count;
while (result.Length < length) is (<color:green>yes)
        #WhiteSmoke:result = chr + result;
endwhile (<color:red>no)
#Lavender:return result;
stop
start
note right:  Program.ReadBigInteger
#LightGreen:Params(string prompt);
#LightSkyBlue:string result
bool validInput;
repeat
        #WhiteSmoke:Print(prompt);
        #WhiteSmoke:result = ReadLine();
        #WhiteSmoke:validInput = IsBigNumber(result);
        if (validInput == false) then (<color:green>yes)
                #WhiteSmoke:PrintLine("Ungültige Eingabe!");
        endif
repeat while (validInput == false) is (<color:green>yes)
#Lavender:return result;
stop
start
note right:  Program.IsBigNumber
#LightGreen:Params(string number);
#LightSkyBlue:bool result = number.Length > 0
int idx = 0;
while (idx < number.Length && result) is (<color:green>yes)
        #WhiteSmoke:result = char.IsDigit(number[idx++]);
endwhile (<color:red>no)
#Lavender:return result;
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
