@startuml Program.ReadBigInteger
title Program.ReadBigInteger
participant "ReadBigInteger(stringprompt)" as ReadBigInteger_p0 #LightYellow
participant "Console.Write(a0)" as Console_Write_a0 #LightGreen
participant "Console.ReadLine()" as Console_ReadLine #LightGreen
participant "IsBigNumber(a0)" as IsBigNumber_a0 #LightGreen
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
autonumber
loop validInput == false
    ReadBigInteger_p0 -> Console_Write_a0 : (prompt)
    ReadBigInteger_p0 -> Console_ReadLine
    Console_ReadLine --> ReadBigInteger_p0 : result
    ReadBigInteger_p0 -> IsBigNumber_a0 : (result)
    IsBigNumber_a0 --> ReadBigInteger_p0 : validInput
    alt validInput == false
        ReadBigInteger_p0 -> Console_WriteLine_a0 : ("Ungültige Eingabe!")
    end
end
@enduml
