@startuml Program.Main
title Program.Main
start
#LightGreen:Params(string[] args);
#WhiteSmoke:PrintLine("Word Shuffle");
#WhiteSmoke:PrintLine("============");
#WhiteSmoke:Print("Please enter 1st word: ");
#LightSkyBlue:string word1 = Console.ReadLine();
#WhiteSmoke:Print("Please enter 2nd word: ");
#LightSkyBlue:string word2 = Console.ReadLine();
#WhiteSmoke:Print("Please enter 1rd word: ");
#LightSkyBlue:string word3 = Console.ReadLine();
#WhiteSmoke:PrintLine("Shuffling words ... six possible combinations:");
#WhiteSmoke:PrintLine();
#WhiteSmoke:PrintLine(word1 + " " + word2 + " " + word3);
#WhiteSmoke:PrintLine(word1 + " " + word3 + " " + word2);
#WhiteSmoke:PrintLine(word2 + " " + word1 + " " + word3);
#WhiteSmoke:PrintLine(word2 + " " + word3 + " " + word1);
#WhiteSmoke:PrintLine(word3 + " " + word1 + " " + word2);
#WhiteSmoke:PrintLine(word3 + " " + word2 + " " + word1);
#WhiteSmoke:PrintLine();
#WhiteSmoke:PrintLine("Press any key to exit: ");
#WhiteSmoke:ReadKey();
stop
@enduml
