@startuml Program.Main
title Program.Main
start
#LightBlue:int counter = 0
string englishWord, germanWord
string translation;
:PrintLine("Lerne die Vokabeln!");
:PrintLine("===================");
:PrintLine();
:PrintLine("* --------------------------- *");
:PrintLine("*      Expertenabschnitt      *");
:PrintLine("* --------------------------- *");
:PrintLine();
:Print("Englisches Wort:      ");
:englishWord = ReadLine()!;
:Print("Deutsche Übersetzung: ");
:germanWord = ReadLine()!;
:Console.Clear();
:PrintLine("* --------------------------- *");
:PrintLine("*      Schülerabschnitt       *");
:PrintLine("* --------------------------- *");
:PrintLine();
:PrintLine($"Gib die deutsche Übersetzung für '{englishWord}' an:");
:PrintLine();
repeat
    :Print($"{++counter}. Versuch: ");
    :translation = ReadLine()!;
repeat while (translation != germanWord && counter < 10) is (<color:green>yes)
if (counter == 1) then (<color:green>yes)
    :PrintLine("Ausgezeichnet, sofort gewußt!");
  else (<color:red>no)
    if ((counter == 2) || (counter == 3)) then (<color:green>yes)
        :PrintLine("Gut gemacht, nur {0} Versuche!", counter);
      else (<color:red>no)
        if ((counter == 4) || (counter == 5)) then (<color:green>yes)
            :PrintLine("Ein bisschen üben, das wird schon.");
          else (<color:red>no)
            if ((counter > 5) && (counter < 10)) then (<color:green>yes)
                :PrintLine("Üben, üben, üben!");
              else (<color:red>no)
                if (counter == 10) then (<color:green>yes)
                    :PrintLine("Das war wohl nichts!!");
                endif
            endif
        endif
    endif
endif
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
@enduml
