@startuml Program.WriteCharacters
header
generated on 3/9/2024 8:21:55 PM
end header
title Program.WriteCharacters
start
#LightBlue:int i = 0;
while (i < count) is (<color:green>yes)
    :Print(character);
:i++;
endwhile (<color:red>no)
:PrintLine();
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
