@startuml Program.SubString
title Program.SubString
start
#Lavender:Params(string text, int startIndex, int length);
#LightBlue:string result = string.Empty;
#LightBlue:int i = startIndex;
while (i >= 0 && i < text.Length && i < startIndex + length) is (<color:green>yes)
    :result += text[i];
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
