@startuml CompleteActivityDiagram
header
generated on 12.03.2024 22:57:10
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#Lavender:Params(string[] args);
#LightBlue:char characterDisplayed
int menueNumber = 0, numChars = 0, numStars = 0, sumOfAllDigits = 0, indexSubString = 0, lengthSubString = 0
string inputSumOfDigits, searchedSubString, inputString;
repeat
    :Console.Clear();
    :PrintLine("Simple Methods");
    :PrintLine("==============");
    :PrintLine();
    :PrintLine("Welche Methode möchten Sie verwenden?");
    :PrintLine("1 ... WriteStars");
    :PrintLine("2 ... WriteCharacters");
    :PrintLine("3 ... SumOfDigits");
    :PrintLine("4 ... SubString");
    :PrintLine("0 ... Exit");
    :Print("Geben Sie eine Zahl ein [1-4]: ");
    :menueNumber = Convert.ToInt32(ReadLine());
    :PrintLine();
    switch (menueNumber)
      case( 1 )
      :Print("Geben Sie die Anzahl der Sterne ein, die Sie anzeigen möchten: ");
      :numStars = Convert.ToInt32(ReadLine());
      :WriteStars(numStars);
      :PrintLine();
      :Print("Weiter mit Eingabe...");
      :ReadLine();
      case( 2 )
      :Print("Geben Sie das Zeichen ein, das Sie anzeigen möchten: ");
      :characterDisplayed = Convert.ToChar(ReadLine());
      :Print($"Geben Sie an, wie oft {characterDisplayed} angezeigt werden soll: ");
      :numChars = Convert.ToInt32(ReadLine());
      :WriteCharacters(numChars, characterDisplayed);
      :PrintLine();
      :Print("Weiter mit Eingabe...");
      :ReadLine();
      case( 3 )
      :Print("Geben Sie Ihren Text ein, sie erhalten eine Zusammenfassung: ");
      :inputSumOfDigits = ReadLine();
      :sumOfAllDigits = SumOfDigits(inputSumOfDigits);
      :PrintLine();
      :PrintLine($"Die Summe aller Zahlen ist gleich {sumOfAllDigits}");
      :Print("Weiter mit Eingabe...");
      :ReadLine();
      case( 4 )
      :Print("Geben Sie Ihren Text ein: ");
      :inputString = ReadLine();
      :Print("Geben Sie den Index ein, an dem der SubString beginnt: ");
      :indexSubString = Convert.ToInt32(ReadLine());
      :Print("Geben Sie die Länge des SubStrings ein: ");
      :lengthSubString = Convert.ToInt32(ReadLine());
      :searchedSubString = SubString(inputString, indexSubString, lengthSubString);
      :PrintLine($"Der Teiltext ist: {searchedSubString}");
      :PrintLine();
      :Print("Weiter mit Eingabe...");
      :ReadLine();
    endswitch
repeat while (menueNumber != 0) is (<color:green>yes)
stop
start
note right:  Program.WriteStars
#Lavender:Params(int count);
#LightBlue:int i = 0;
while (i < count) is (<color:green>yes)
    :Print("*");
:i++;
endwhile (<color:red>no)
:PrintLine();
stop
start
note right:  Program.WriteCharacters
#Lavender:Params(int count, char character);
#LightBlue:int i = 0;
while (i < count) is (<color:green>yes)
    :Print(character);
:i++;
endwhile (<color:red>no)
:PrintLine();
stop
start
note right:  Program.SumOfDigits
#Lavender:Params(string text);
#LightBlue:int result = 0;
#LightBlue:int i = 0;
while (i < text.Length) is (<color:green>yes)
    if (Char.IsDigit(text[i])) then (<color:green>yes)
        :result += text[i] - '0';
    endif
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
start
note right:  Program.SubString
#Lavender:Params(string text, int startIndex, int length);
#LightBlue:string result = string.Empty;
#LightBlue:int i = startIndex;
while (i >= 0 && i < text.Length && i < startIndex + length) is (<color:green>yes)
    :result += text[i];
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
