@startuml Program.WriteStars
title Program.WriteStars
participant "WriteStars(intcount)" as WriteStars_p0 #LightYellow
participant "Console.Write(a0)" as Console_Write_a0 #LightGreen
participant "Console.WriteLine()" as Console_WriteLine #LightGreen
autonumber
loop#LightCoral i < count
    WriteStars_p0 -[#grey]> Console_Write_a0 : ("*")
end
WriteStars_p0 -[#grey]> Console_WriteLine
@enduml
