@startuml CompleteActivityDiagram
header
generated on 3/9/2024 7:37:48 PM
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#LightBlue:string input, output
string operation
double leftOpd, rightOpd, result;
:PrintLine("Einfacher Rechner");
:PrintLine("=================");
:Print("Linker Operand [double]: ");
:input = ReadLine();
:leftOpd = Convert.ToDouble(input);
:Print("Operation [+ - * /]: ");
:operation = ReadLine();
:Print("Rechter Operand [double]: ");
:input = ReadLine();
:rightOpd = Convert.ToDouble(input);
if (operation == "+") then (<color:green>yes)
    :result = leftOpd + rightOpd;
    :output = ($"Ergebnis von {leftOpd} + {rightOpd} = {result}");
  else (<color:red>no)
    if (operation == "-") then (<color:green>yes)
        :result = leftOpd - rightOpd;
        :output = ($"Ergebnis von {leftOpd} - {rightOpd} = {result}");
      else (<color:red>no)
        if (operation == "*") then (<color:green>yes)
            :result = leftOpd * rightOpd;
            :output = ($"Ergebnis von {leftOpd} * {rightOpd} = {result}");
          else (<color:red>no)
            if (operation == "/") then (<color:green>yes)
                :result = leftOpd / rightOpd;
                :output = ($"Ergebnis von {leftOpd} / {rightOpd} = {result}");
              else (<color:red>no)
                  :output = "Ungültige Eingabe!";
            endif
        endif
    endif
endif
:PrintLine(output);
:PrintLine("Beenden mit der Eingabetaste");
:ReadLine();
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
