@startuml Program.FilterVocals
title Program.FilterVocals
start
#LightGreen:Params(string input);
#LightSkyBlue:string result = string.Empty;
#LightSkyBlue:int i = 0;
while (i < input.Length) is (<color:green>yes)
        #LightSkyBlue:char chr = char.ToLower(input[i]);
        if (chr == 'a' || chr == 'e' || chr == 'i' || chr == 'o' || chr == 'u') then (<color:green>yes)
                if (result.Contains(input[i]) == false) then (<color:green>yes)
                        #WhiteSmoke:result += input[i];
                endif
        endif
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
