@startuml Program.FilterVocals
title Program.FilterVocals
start
:string result = string.Empty;
:int i = 0;
while (i < input.Length) is (yes)
    :char chr = char.ToLower(input[i]);
    if (chr == 'a' || chr == 'e' || chr == 'i' || chr == 'o' || chr == 'u') then (yes)
        if (result.Contains(input[i]) == false) then (yes)
            :result += input[i];
        endif
    endif
:i++;
endwhile (no)
stop
@enduml
