@startuml CompleteActivityDiagram
header
generated on 12.03.2024 22:57:03
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#Lavender:Params(string[] args);
#LightBlue:string input
int sum = 0, prvMax = Int32.MinValue, max = Int32.MinValue, min = Int32.MaxValue, num = 0, idx = 0
double average = 0;
:PrintLine(" Zahlen Statistik ");
:PrintLine("==================");
:PrintLine();
:PrintLine("Geben Sie positive ganze Zahlen ein [0..Ende]");
repeat
    :idx = idx + 1;
    :Print($"Zahl {idx}: ");
    :input = ReadLine();
    :num = Convert.ToInt32(input);
    if (num != 0) then (<color:green>yes)
        :sum = sum + num;
        if (num > max) then (<color:green>yes)
            :prvMax = max;
            :max = num;
          else (<color:red>no)
            if (num > prvMax && num < max) then (<color:green>yes)
                :prvMax = num;
            endif
        endif
        if (num < min) then (<color:green>yes)
            :min = num;
        endif
        :average = sum / (double)idx;
    endif
repeat while (num != 0) is (<color:green>yes)
:PrintLine();
if (idx > 1) then (<color:green>yes)
    :PrintLine($"Sie haben {idx - 1} Zahlen eingegeben.");
    :PrintLine($"Die Summe der eingegebenen Zahlen ist {sum}.");
    :PrintLine($"Der maximale Wert ist {max}.");
    if (idx > 2) then (<color:green>yes)
        :PrintLine($"Die zweitgrößte Zahl ist {prvMax}.");
    endif
    :PrintLine($"Der minimale Wert ist {min}.");
    :PrintLine($"Der Durchschnittswert ist {average:f}");
endif
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
