@startuml Program.Main
title Program.Main
start
#LightGreen:Params(string[] args);
#WhiteSmoke:PrintLine("Visitenkarte");
#LightSkyBlue:string username, adress;
#WhiteSmoke:Print("Write your name:   ");
#WhiteSmoke:username = ReadLine();
#WhiteSmoke:Print("write your adress: ");
#WhiteSmoke:adress = ReadLine();
#WhiteSmoke:PrintLine();
#WhiteSmoke:PrintLine("****************************************");
#WhiteSmoke:Print($"* {username,-37}");
#WhiteSmoke:PrintLine("*");
#WhiteSmoke:PrintLine("****************************************");
#WhiteSmoke:Print($"* {adress,-37}");
#WhiteSmoke:PrintLine("*");
#WhiteSmoke:PrintLine("****************************************");
stop
@enduml
