@startuml CompleteActivityDiagram
header
generated on 3/9/2024 7:37:48 PM
end header
title CompleteActivityDiagram
start
note right:  Program.Main
:PrintLine("Visitenkarte");
#LightBlue:string username, adress;
:Print("Write your name:   ");
:username = ReadLine();
:Print("write your adress: ");
:adress = ReadLine();
:PrintLine();
:PrintLine("****************************************");
:Print($"* {username,-37}");
:PrintLine("*");
:PrintLine("****************************************");
:Print($"* {adress,-37}");
:PrintLine("*");
:PrintLine("****************************************");
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
