@startuml CompleteActivityDiagram
header
generated on 09.04.2024 22:12:00
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#LightGreen:Params(string[] args);
#WhiteSmoke:PrintLine("Visitenkarte");
#LightSkyBlue:string username, adress;
#WhiteSmoke:Print("Write your name:   ");
#WhiteSmoke:username = ReadLine();
#WhiteSmoke:Print("write your adress: ");
#WhiteSmoke:adress = ReadLine();
#WhiteSmoke:PrintLine();
#WhiteSmoke:PrintLine("****************************************");
#WhiteSmoke:Print($"* {username,-37}");
#WhiteSmoke:PrintLine("*");
#WhiteSmoke:PrintLine("****************************************");
#WhiteSmoke:Print($"* {adress,-37}");
#WhiteSmoke:PrintLine("*");
#WhiteSmoke:PrintLine("****************************************");
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
