@startuml Program.Main
title Program.Main
start
:PrintLine("Visitenkarte");
:string username, adress;
:Print("Write your name:   ");
:username = ReadLine();
:Print("write your adress: ");
:adress = ReadLine();
:PrintLine();
:PrintLine("****************************************");
:Print($"* {username,-37}");
:PrintLine("*");
:PrintLine("****************************************");
:Print($"* {adress,-37}");
:PrintLine("*");
:PrintLine("****************************************");
stop
@enduml
