@startuml Program.Main
title Program.Main
start
:PrintLine("Einfacher Rechner");
:PrintLine("=================");
:Print("Linker Operand [double]: ");
:input = ReadLine();
:leftOpd = Convert.ToDouble(input);
:Print("Operation [+ - * /]: ");
:operation = ReadLine();
:Print("Rechter Operand [double]: ");
:input = ReadLine();
:rightOpd = Convert.ToDouble(input);
if (operation == "+") then (yes)
    :result = leftOpd + rightOpd;
    :output = ($"Ergebnis von {leftOpd} + {rightOpd} = {result}");
  else (no)
    if (operation == "-") then (yes)
        :result = leftOpd - rightOpd;
        :output = ($"Ergebnis von {leftOpd} - {rightOpd} = {result}");
      else (no)
        if (operation == "*") then (yes)
            :result = leftOpd * rightOpd;
            :output = ($"Ergebnis von {leftOpd} * {rightOpd} = {result}");
          else (no)
            if (operation == "/") then (yes)
                :result = leftOpd / rightOpd;
                :output = ($"Ergebnis von {leftOpd} / {rightOpd} = {result}");
              else (no)
                  :output = "Ungültige Eingabe!";
            endif
        endif
    endif
endif
:PrintLine(output);
:PrintLine("Beenden mit der Eingabetaste");
:ReadLine();
stop
@enduml
