@startuml Program.Main
title Program.Main
start
#LightGreen:Params(string[] args);
#LightSkyBlue:string input, operation\ndouble left, right, result;
#WhiteSmoke:PrintLine("CalculatorWithSwitch");
#WhiteSmoke:PrintLine("====================");
#WhiteSmoke:PrintLine();
#WhiteSmoke:Print("Eingabe Zahl 1: ");
#WhiteSmoke:input = ReadLine();
#WhiteSmoke:left = Convert.ToDouble(input);
#WhiteSmoke:Print("Eingabe Zahl 2: ");
#WhiteSmoke:input = ReadLine();
#WhiteSmoke:right = Convert.ToDouble(input);
#WhiteSmoke:Print("Eingabe Operation [+, -, *, /]: ");
#WhiteSmoke:operation = ReadLine();
switch (operation)
    case( "+" )
    #WhiteSmoke:result = left + right;
    case( "-" )
    #WhiteSmoke:result = left - right;
    case( "*" )
    #WhiteSmoke:result = left * right;
    case( "/" )
    #WhiteSmoke:result = left / right;
    case ( default )
    #WhiteSmoke:result = 0;
endswitch
#WhiteSmoke:PrintLine();
if (operation == "+" || operation == "-" || operation == "*" || operation == "/") then (<color:green>yes)
        #WhiteSmoke:PrintLine($"{left,10:f}");
        #WhiteSmoke:PrintLine($"{operation}{right,9:f}");
        #WhiteSmoke:PrintLine("----------");
        #WhiteSmoke:PrintLine($"{result,10:f}");
    else (<color:red>no)
            #WhiteSmoke:PrintLine("Ungültige Operation!");
endif
#WhiteSmoke:PrintLine();
#WhiteSmoke:PrintLine("Press any key to exit: ");
#WhiteSmoke:ReadKey();
stop
@enduml
