@startuml CompleteActivityDiagram
header
generated on 3/9/2024 8:21:55 PM
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#LightBlue:string input, operation
double left, right, result;
:PrintLine("CalculatorWithSwitch");
:PrintLine("====================");
:PrintLine();
:Print("Eingabe Zahl 1: ");
:input = ReadLine();
:left = Convert.ToDouble(input);
:Print("Eingabe Zahl 2: ");
:input = ReadLine();
:right = Convert.ToDouble(input);
:Print("Eingabe Operation [+, -, *, /]: ");
:operation = ReadLine();
switch (operation)
  case( "+" )
  :result = left + right;
  case( "-" )
  :result = left - right;
  case( "*" )
  :result = left * right;
  case( "/" )
  :result = left / right;
  case ( default )
  :result = 0;
endswitch
:PrintLine();
if (operation == "+" || operation == "-" || operation == "*" || operation == "/") then (<color:green>yes)
    :PrintLine($"{left,10:f}");
    :PrintLine($"{operation}{right,9:f}");
    :PrintLine("----------");
    :PrintLine($"{result,10:f}");
  else (<color:red>no)
      :PrintLine("Ungültige Operation!");
endif
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
