@startuml Program.AnalyzeLottery
title Program.AnalyzeLottery
start
#LightBlue:int[] result = new int[TIP_SIZE + 1];
#LightBlue:int i = 0;
while (i < lottoTipps.GetLength(0)) is (<color:green>yes)
    #LightBlue:int hits = CountNumberOfHits(i, lottoTipps, thrownNumbers);
    :result[hits]++;
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
