@startuml Program.EqualsTo
title Program.EqualsTo
start
#LightBlue:int idx = 0
bool result = arrayOne.Length == arrayTwo.Length;
while (result && idx < arrayOne.Length) is (<color:green>yes)
    :result = arrayOne[idx] == arrayTwo[idx];
    :idx++;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
