@startuml Program.Main
title Program.Main
start
#LightBlue:int[] results
int[] correctResult = { 400874, 423358, 151635, 22687, 1416, 30, 0 }
int[] thrownNumbers
int[,] lottoTipps = CreateTipps(TIPPS_COUNT)
Stopwatch stopWatch = new Stopwatch();
:PrintLine("Lottosimulator");
:PrintLine("==============");
:PrintLine();
:PrintLine("{0} Tippkolonnen", lottoTipps.GetLength(0));
:PrintLine();
:thrownNumbers = CreateTip();
:stopWatch.Start();
:results = AnalyzeLottery(lottoTipps, thrownNumbers);
:stopWatch.Stop();
:PrintResult(results);
:PrintLine();
if (EqualsTo(results, correctResult)) then (<color:green>yes)
    :PrintLine("Das Ergebnis ist richtig!");
  else (<color:red>no)
      :PrintLine("Für 1 Mio Versuche ist das Ergebnis falsch!");
endif
:PrintLine("Rechenzeit: {0} Millisekunden!", stopWatch.ElapsedMilliseconds);
:PrintLine("Exit with Enter...");
:ReadLine();
stop
@enduml
