@startuml Program.PrintResult
title Program.PrintResult
start
#LightBlue:int resultSum = 0;
#LightBlue:int i = TIP_SIZE;
while (i >= 0) is (<color:green>yes)
    :PrintLine($"{i}er: {results[i], 10}");
    :resultSum += results[i];
:i--;
endwhile (<color:red>no)
:PrintLine(new string('-' , 20));
:PrintLine($"Summe: {resultSum, 8}");
stop
@enduml
