@startuml Program.CreateTipps
title Program.CreateTipps
start
#Lavender:Params(int countTipps);
#LightBlue:int[,] result = new int[countTipps, TIP_SIZE];
#LightBlue:int tippNummer = 0;
while (tippNummer < countTipps) is (<color:green>yes)
    #LightBlue:int[] tip = CreateTip();
    #LightBlue:int zahlNummer = 0;
    while (zahlNummer < 6) is (<color:green>yes)
        :result[tippNummer, zahlNummer] = tip[zahlNummer];
    :zahlNummer++;
    endwhile (<color:red>no)
:tippNummer++;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
