@startuml Program.CountNumberOfHits
title Program.CountNumberOfHits
start
#Lavender:Params(int index, int[,] tipps, int[] thrownNumbers);
#LightBlue:int result = 0;
#LightBlue:int i = 0;
while (i < tipps.GetLength(1)) is (<color:green>yes)
    #LightBlue:int j = 0;
    while (j < thrownNumbers.Length) is (<color:green>yes)
        if (tipps[index, i] == thrownNumbers[j]) then (<color:green>yes)
            :result++;
        endif
    :j++;
    endwhile (<color:red>no)
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
