@startuml Program.CreateTip
title Program.CreateTip
participant "CreateTip" as CreateTip #LightYellow
participant "random.Next(a0,a1)" as random_Next_a0_a1 #LightGreen
autonumber
loop found
    CreateTip -> random_Next_a0_a1 : (MIN_NUMBER, MAX_NUMBER + 1)
    random_Next_a0_a1 --> CreateTip : number
end
@enduml
