@startuml CompleteActivityDiagram
header
generated on 09/04/2024 14:47:12
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#LightGreen:Params(string[] args);
#LightSkyBlue:string name, input\ndouble hours, pricePerHour, salary;
#WhiteSmoke:PrintLine("***************************************************");
#WhiteSmoke:PrintLine("* Der Lohnrechner für eine gerechte Entlohnung!   *");
#WhiteSmoke:PrintLine("***************************************************");
#WhiteSmoke:Print("Name des Arbeiters:        ");
#WhiteSmoke:name = ReadLine();
#WhiteSmoke:Print("Anzahl der Arbeitsstunden: ");
#WhiteSmoke:hours = Convert.ToDouble(ReadLine());
#WhiteSmoke:Print("Stundenlohn:               ");
#WhiteSmoke:input = ReadLine();
#WhiteSmoke:pricePerHour = Convert.ToDouble(input);
#WhiteSmoke:salary = hours * pricePerHour;
#WhiteSmoke:PrintLine();
#WhiteSmoke:PrintLine($"{name} hat in {hours:f} Stunden {salary} EUR verdient.");
#WhiteSmoke:PrintLine();
#WhiteSmoke:Print("Zum Beenden Eingabetaste drücken...");
#WhiteSmoke:ReadLine();
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
