@startuml Program.Main
title Program.Main
start
:PrintLine("***************************************************");
:PrintLine("* Vocal Filter with Method                        *");
:PrintLine("***************************************************");
:PrintLine();
:Print("Eingabetext: ");
:input = ReadLine();
:output = FilterVocals(input);
:PrintLine($"Ausgabetext: {output}");
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
@enduml
