@startuml Program.ReadPosturePoints
title Program.ReadPosturePoints
start
while (idx < count) is (yes)
    :Print($"Wertungsrichter {idx + 1} [0-20]: ");
    :input = ReadLine();
    if (double.TryParse(input, out result[idx]) 
                    && result[idx] >= 0 
                    && result[idx] <= 20 
                    && (result[idx] % 1 == 0 || result[idx] % 1 == 0.5)) then (yes)
        :idx++;
      else (no)
          :PrintLine("Ungültige Eingabe!");
    endif
endwhile (no)
stop
@enduml
