@startuml Program.CalculatePosturePoints
title Program.CalculatePosturePoints
start
:int i = 0;
while (i < posturePoints.Length) is (yes)
    if (posturePoints[i] > max) then (yes)
        :max = posturePoints[i];
    endif
    if (posturePoints[i] < min) then (yes)
        :min = posturePoints[i];
    endif
    :result += posturePoints[i];
:i++;
endwhile (no)
stop
@enduml
