@startuml CompleteActivityDiagram
header
generated on 05.03.2024 11:15:20
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#LightBlue:string input
double distance, speed, time
int hour, min, sec, timeInSec;
:PrintLine("***************************************************");
:PrintLine("* Lieblingstante - Die Fahrt zu meiner Tante      *");
:PrintLine("*                  Berechnung der Ankunftszeit    *");
:PrintLine("***************************************************");
:PrintLine();
:Print("Enfernung in km:         ");
:input = ReadLine();
:distance = Convert.ToDouble(input);
:Print("Geschwindigkeit in km/h: ");
:input = ReadLine();
:speed = Convert.ToDouble(input);
:time = distance / speed;
:timeInSec = (int)(time * 3600);
:hour = 10 + ((timeInSec / 3600) % 24);
:min = (timeInSec % 3600) / 60;
:sec = timeInSec % 60;
:PrintLine();
:PrintLine($"Für die Strecke von {distance:f2} benötigen Sie {time:f2} Stunden.");
:PrintLine($"Sie kommen um {hour:D2}:{min:D2}:{sec:D2} an.");
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
