@startuml CompleteActivityDiagram
header
generated on 12.03.2024 22:57:03
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#Lavender:Params(string[] args);
#LightBlue:string input
int nOne, nTwo, nThree, nMax, nMin;
:PrintLine("MinMax Calculator");
:PrintLine("=================");
:PrintLine();
:Print("Eingabe Zahl 1: ");
:input = ReadLine();
:nOne = Convert.ToInt32(input);
:Print("Eingabe Zahl 2: ");
:input = ReadLine();
:nTwo = Convert.ToInt32(input);
:Print("Eingabe Zahl 3: ");
:input = ReadLine();
:nThree = Convert.ToInt32(input);
if (nOne >= nTwo && nTwo >= nThree) then (<color:green>yes)
    :nMax = nOne;
  else (<color:red>no)
    if (nTwo >= nOne && nOne >= nThree) then (<color:green>yes)
        :nMax = nTwo;
      else (<color:red>no)
          :nMax = nThree;
    endif
endif
if (nOne <= nTwo && nTwo <= nThree) then (<color:green>yes)
    :nMin = nOne;
  else (<color:red>no)
    if (nTwo <= nOne && nOne <= nThree) then (<color:green>yes)
        :nMin = nTwo;
      else (<color:red>no)
          :nMin = nThree;
    endif
endif
:PrintLine();
:PrintLine($"Max = {nMax, 10}");
:PrintLine($"Min = {nMin, 10}");
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
