@startuml Program.Main
title Program.Main
participant "Main(string[]args)" as Main_p0 #LightYellow
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
participant "Console.WriteLine()" as Console_WriteLine #LightGreen
participant "Console.Write(a0)" as Console_Write_a0 #LightGreen
participant "Console.ReadLine()" as Console_ReadLine #LightGreen
participant "Convert.ToInt32(a0)" as Convert_ToInt32_a0 #LightGreen
participant "Console.ReadKey()" as Console_ReadKey #LightGreen
autonumber
Main_p0 -[#grey]> Console_WriteLine_a0 : ("MinMax Calculator")
Main_p0 -[#grey]> Console_WriteLine_a0 : ("=================")
Main_p0 -[#grey]> Console_WriteLine
Main_p0 -[#grey]> Console_Write_a0 : ("Eingabe Zahl 1: ")
Main_p0 -[#grey]> Console_ReadLine
Console_ReadLine -[#blue]-> Main_p0 : input
Main_p0 -[#grey]> Convert_ToInt32_a0 : (input)
Convert_ToInt32_a0 -[#blue]-> Main_p0 : nOne
Main_p0 -[#grey]> Console_Write_a0 : ("Eingabe Zahl 2: ")
Main_p0 -[#grey]> Console_ReadLine
Console_ReadLine -[#blue]-> Main_p0 : input
Main_p0 -[#grey]> Convert_ToInt32_a0 : (input)
Convert_ToInt32_a0 -[#blue]-> Main_p0 : nTwo
Main_p0 -[#grey]> Console_Write_a0 : ("Eingabe Zahl 3: ")
Main_p0 -[#grey]> Console_ReadLine
Console_ReadLine -[#blue]-> Main_p0 : input
Main_p0 -[#grey]> Convert_ToInt32_a0 : (input)
Convert_ToInt32_a0 -[#blue]-> Main_p0 : nThree
Main_p0 -[#grey]> Console_WriteLine
Main_p0 -[#grey]> Console_WriteLine_a0 : ($"Max = {nMax, 10}")
Main_p0 -[#grey]> Console_WriteLine_a0 : ($"Min = {nMin, 10}")
Main_p0 -[#grey]> Console_WriteLine
Main_p0 -[#grey]> Console_WriteLine_a0 : ("Press any key to exit: ")
Main_p0 -[#grey]> Console_ReadKey
@enduml
