@startuml Program.Main
title Program.Main
start
#LightBlue:string input, encrypted, decrypted;
:PrintLine("***************************************************");
:PrintLine("* Einfache Verschlüsselung nach ROT13             *");
:PrintLine("***************************************************");
:PrintLine();
:Print("Zu verschlüsselnden Text: ");
:input = ReadLine();
:encrypted = Encrypt(input);
:PrintLine($"Verschlüsselter Text: {encrypted}");
:decrypted = Decrypt(encrypted);
:PrintLine($"Entschlüsselter Text: {decrypted}");
:PrintLine();
:Print("Press enter to exit...");
:ReadLine();
stop
@enduml
