@startuml Program.Decrypt
header
generated on 3/9/2024 8:21:55 PM
end header
title Program.Decrypt
start
#Lavender:return Encrypt(encrypted);
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
