@startuml Program.Encrypt
title Program.Encrypt
start
#Lavender:Params(string input);
#LightBlue:string result = string.Empty;
#LightBlue:int i = 0;
while (i < input.Length) is (<color:green>yes)
    #LightBlue:char chr = char.ToLower(input[i]);
    if (chr >= 'a' && chr <= 'm') then (<color:green>yes)
        :chr = Convert.ToChar(input[i] + 13);
      else (<color:red>no)
        if (chr >= 'n' && chr <= 'z') then (<color:green>yes)
            :chr = Convert.ToChar(input[i] - 13);
        endif
    endif
    :result += chr;
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
