@startuml Stack.Push
title Stack.Push
start
#LightGreen:Params(double data);
#WhiteSmoke:_head = new Element(data, _head);
#WhiteSmoke:ObjectDiagram.Create(this, $"title Stack after Push({data})");
stop
@enduml
