@startuml ObjectDiagram
title ObjectDiagram
 class ObjectDiagram << static >> #GhostWhite {
+ {const} string FilePath = @"/Users/ggehrer/source/Test/UPNCalculator/od_Stack.puml"
---
---
+ {static} void Generate(object obj)
}
@enduml
