@startuml CompleteClassDiagram
title CompleteClassDiagram
 class Element #GhostWhite {
- double _data
- Element? _next
---
+ double getData()
+ Void setData(double value)
+ Element? getNext()
+ Void setNext(Element? value)
---
}
 class Program #GhostWhite {
---
---
- {static} void Main(string[] args)
- {static} double Parse(string input)
}
 class ObjectDiagram << static >> #GhostWhite {
+ {const} string FilePath = @"/Users/ggehrer/source/Test/UPNCalculator/od_Stack.puml"
---
---
+ {static} void Generate(object obj)
}
 class Stack #GhostWhite {
- Element? head = null
---
+ bool getIsEmpty()
---
+ void Push(double data)
+ double Pop()
}
Element *-- Element : _next
Stack *-- Element : head
' CustomUML
' Stack *-- Element
' CustomUML
@enduml
