@startuml CompleteClassDiagram
title CompleteClassDiagram
class Element #GhostWhite {
- double _data
- Element? _next
---
+ double getData()
+ Void setData(double value)
+ Element? getNext()
+ Void setNext(Element? value)
---
}
class Program #GhostWhite {
---
---
- {static} void Main(string[] args)
- {static} double Parse(string input)
}
class Stack #GhostWhite {
- Element? _head = null
---
+ bool getIsEmpty()
---
+ void Push(double data)
+ double Pop()
}
Element "0..1" *-- "1" Element : _next
Stack "0..1" *-- "1" Element : _head
' CustomUML
Program "0..1" *-- "1" Stack 
note right of Program
Parse uses Stack
end note
' CustomUML
@enduml
