@startuml ObjectDiagram.Generate
title ObjectDiagram.Generate
participant "Generate(object obj)" as Generate_p0 #LightYellow
participant "DiagramCreator.CreateObjectDiagram(100,obj).ToList()" as DiagramCreator_CreateObjectDiagram_100_obj_ToList #LightGreen
participant "diagramData.Any()" as diagramData_Any #LightGreen
participant "diagramData.Insert(a0,a1)" as diagramData_Insert_a0_a1 #LightGreen
participant "diagramData.Add(a0)" as diagramData_Add_a0 #LightGreen
participant "File.WriteAllLines(a0,a1)" as File_WriteAllLines_a0_a1 #LightGreen
autonumber
Generate_p0 -[#grey]> DiagramCreator_CreateObjectDiagram_100_obj_ToList
DiagramCreator_CreateObjectDiagram_100_obj_ToList -[#blue]-> Generate_p0 : diagramData
alt#LightBlue diagramData.Any()
 Generate_p0 -[#grey]> diagramData_Any
 Generate_p0 -[#grey]> diagramData_Insert_a0_a1 : (0, "@start" + "uml stack")
 Generate_p0 -[#grey]> diagramData_Add_a0 : ("@end" + "uml")
end
Generate_p0 -[#grey]> File_WriteAllLines_a0_a1 : (FilePath, diagramData)
@enduml
