@startuml Stack.Pop
title Stack.Pop
participant "Pop" as Pop #LightYellow
participant "ObjectDiagram.Create(a0,a1)" as ObjectDiagram_Create_a0_a1 #LightGreen
autonumber
Pop -[#grey]> ObjectDiagram_Create_a0_a1 : (this, $"title Stack after Pop() => { Expression }")
@enduml
