@startuml Program.CompareAndPrintMatrix
title Program.CompareAndPrintMatrix
start
#LightBlue:ConsoleColor originalColor = Console.ForegroundColor;
#LightBlue:int r = 0;
while (r < matrix.GetLength(0)) is (<color:green>yes)
    :CompareAndPrintMatrixValues(matrix, r);
    :PrintLine();
    if (r < matrix.GetLength(0) - 1) then (<color:green>yes)
        :CompareAndPrintMatrixRows(matrix, r, r + 1);
        :PrintLine();
    endif
:r++;
endwhile (<color:red>no)
:PrintLine();
:Console.ForegroundColor = originalColor;
stop
@enduml
