@startuml Program.Main
title Program.Main
participant "Main" as Main #LightYellow
participant "ReadMatrixDimensions(a0,a1)" as ReadMatrixDimensions_a0_a1 #LightGreen
participant "CreateMatrix(a0,a1)" as CreateMatrix_a0_a1 #LightGreen
participant "CompareAndPrintMatrix(a0)" as CompareAndPrintMatrix_a0 #LightGreen
participant "Console.Write(a0)" as Console_Write_a0 #LightGreen
participant "Console.ReadLine()" as Console_ReadLine #LightGreen
participant "input.ToLower()" as input_ToLower #LightGreen
autonumber
loop#LightCoral input.ToLower() == "j"
    Main -[#grey]> ReadMatrixDimensions_a0_a1 : (out rows, out cols)
    Main -[#grey]> CreateMatrix_a0_a1 : (rows, cols)
    CreateMatrix_a0_a1 -[#blue]-> Main : matrix
    Main -[#grey]> CompareAndPrintMatrix_a0 : (matrix)
    Main -[#grey]> Console_Write_a0 : ("Weitere Matrix anzeigen (j/n)? ")
    Main -[#grey]> Console_ReadLine
    Console_ReadLine -[#blue]-> Main : input
    Main -[#grey]> input_ToLower
    input_ToLower -[#blue]-> Main : result
end
@enduml
