@startuml Program.Main
title Program.Main
start
#LightGreen:Params(string[] args);
#LightSkyBlue:string input\nint number1, number2, sum;
#WhiteSmoke:PrintLine("****************************************");
#WhiteSmoke:PrintLine("* Calculator - Ihr Zahlenbegleiter     *");
#WhiteSmoke:PrintLine("****************************************");
#WhiteSmoke:Print("Erste Zahl:  ");
#WhiteSmoke:input = ReadLine();
#WhiteSmoke:number1 = Convert.ToInt32(input);
#WhiteSmoke:Print("Zweite Zahl: ");
#WhiteSmoke:input = ReadLine();
#WhiteSmoke:number2 = Convert.ToInt32(input);
#WhiteSmoke:sum = number1 + number2;
#WhiteSmoke:PrintLine("Ergebnis:");
#WhiteSmoke:PrintLine("====================");
#WhiteSmoke:PrintLine($"{number1,20}");
#WhiteSmoke:PrintLine($"+{number2,19}");
#WhiteSmoke:PrintLine("--------------------");
#WhiteSmoke:PrintLine($"{sum,20}");
#WhiteSmoke:PrintLine("====================");
stop
@enduml
