@startuml Program.IsBigNumber
title Program.IsBigNumber
start
#LightGreen:Params(string number);
#LightSkyBlue:bool result = number.Length > 0
int idx = 0;
while (idx < number.Length && result) is (<color:green>yes)
    #WhiteSmoke:result = char.IsDigit(number[idx++]);
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
