@startuml Program.ReadBigInteger
title Program.ReadBigInteger
start
#LightGreen:Params(string prompt);
#LightSkyBlue:string result
bool validInput;
repeat
        #WhiteSmoke:Print(prompt);
        #WhiteSmoke:result = ReadLine();
        #WhiteSmoke:validInput = IsBigNumber(result);
        if (validInput == false) then (<color:green>yes)
                #WhiteSmoke:PrintLine("Ungültige Eingabe!");
        endif
repeat while (validInput == false) is (<color:green>yes)
#Lavender:return result;
stop
@enduml
