@startuml Program.ReadBigInteger
title Program.ReadBigInteger
start
#LightBlue:string result
bool validInput;
repeat
    :Print(prompt);
    :result = ReadLine();
    :validInput = IsBigNumber(result);
    if (validInput == false) then (<color:green>yes)
        :PrintLine("Ungültige Eingabe!");
    endif
repeat while (validInput == false) is (<color:green>yes)
#Lavender:return result;
stop
@enduml
