@startuml Program.ReadBigInteger
title Program.ReadBigInteger
participant "ReadBigInteger(string prompt)" as ReadBigInteger_p0 #LightYellow
participant "Console.Write(a0)" as Console.Write_a0 #LightGreen
participant "Console.ReadLine()" as Console.ReadLine #LightGreen
participant "IsBigNumber(a0)" as IsBigNumber_a0 #LightGreen
participant "Console.WriteLine(a0)" as Console.WriteLine_a0 #LightGreen
autonumber
@enduml
