@startuml CompleteClassDiagram
title CompleteClassDiagram
 class Program #GhostWhite {
---
---
- {static} void Main(string[] args)
- {static} long FibonacciRecursive(int n)
- {static} long FibonacciIterative(int n)
}
@enduml
