@startuml Program.Main
title Program.Main
start
:string input, splitText;
:PrintLine("***************************************************");
:PrintLine("* StringSplit - Ein einfacher Textsplit           *");
:PrintLine("***************************************************");
:PrintLine();
:Print("Eingabetext:  ");
:input = ReadLine();
repeat
    :Print("Splitzeichen: ");
    :splitText = ReadLine();
repeat while (splitText.Length != 1) is (yes)
:PrintLine("*** Ausgabetext ***");
:int i = 0;
while (i < input.Length) is (yes)
    if (input[i] == splitText[0]) then (yes)
        :PrintLine();
      else (no)
          :Print(input[i]);
    endif
:i++;
endwhile (no)
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
@enduml
