@startuml Program.Main
title Program.Main
participant "Main(string[]args)" as Main_p0 #LightYellow
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
participant "Console.WriteLine()" as Console_WriteLine #LightGreen
participant "Console.Write(a0)" as Console_Write_a0 #LightGreen
participant "Console.ReadLine()" as Console_ReadLine #LightGreen
participant "Console.ReadKey()" as Console_ReadKey #LightGreen
autonumber
Main_p0 -> Console_WriteLine_a0 : ("***************************************************")
Main_p0 -> Console_WriteLine_a0 : ("* StringSplit - Ein einfacher Textsplit           *")
Main_p0 -> Console_WriteLine_a0 : ("***************************************************")
Main_p0 -> Console_WriteLine
Main_p0 -> Console_Write_a0 : ("Eingabetext:  ")
Main_p0 -> Console_ReadLine
Console_ReadLine --> Main_p0 : input
loop splitText.Length != 1
    Main_p0 -> Console_Write_a0 : ("Splitzeichen: ")
    Main_p0 -> Console_ReadLine
    Console_ReadLine --> Main_p0 : splitText
end
Main_p0 -> Console_WriteLine_a0 : ("*** Ausgabetext ***")
loop i < input.Length
    alt input[i] == splitText[0]
        Main_p0 -> Console_WriteLine
        else
            Main_p0 -> Console_Write_a0 : (input[i])
    end
end
Main_p0 -> Console_WriteLine
Main_p0 -> Console_WriteLine_a0 : ("Press any key to exit: ")
Main_p0 -> Console_ReadKey
@enduml
