@startuml Program.Main
header
generated on 3/9/2024 8:21:55 PM
end header
title Program.Main
start
#LightBlue:string inputText, eliminatorText, outputText;
:PrintLine("Delete Chars!");
:PrintLine("=============");
:outputText = string.Empty;
:PrintLine();
:Print("Eingabetext....: ");
:inputText = ReadLine();
if (inputText != "") then (<color:green>yes)
    :Print("Eliminatortext..: ");
    :eliminatorText = ReadLine();
    #LightBlue:int i = 0;
    while (i < inputText.Length) is (<color:green>yes)
        #LightBlue:bool contains = false;
        #LightBlue:int j = 0;
        while (j < eliminatorText.Length && contains == false) is (<color:green>yes)
            if (inputText[i] == eliminatorText[j]) then (<color:green>yes)
                :contains = true;
            endif
        :j++;
        endwhile (<color:red>no)
        if (contains == false) then (<color:green>yes)
            :outputText = outputText + inputText[i];
        endif
    :i++;
    endwhile (<color:red>no)
    :PrintLine();
    :PrintLine($"Ausgabetext....: {outputText}");
    :Print("Weiter mit beliebiger Taste ...");
    :ReadKey();
endif
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
