@startuml Program.Main
title Program.Main
participant "Main(string[] args)" as Main_p0 #LightYellow
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
participant "Console.WriteLine()" as Console_WriteLine #LightGreen
participant "Console.Write(a0)" as Console_Write_a0 #LightGreen
participant "Console.ReadLine()" as Console_ReadLine #LightGreen
participant "Parse(a0)" as Parse_a0 #LightGreen
autonumber
Main_p0 -[#grey]> Console_WriteLine_a0 : ("**********************")
Main_p0 -[#grey]> Console_WriteLine_a0 : ("* StackCalculator    *")
Main_p0 -[#grey]> Console_WriteLine_a0 : ("**********************")
Main_p0 -[#grey]> Console_WriteLine
loop#LightCoral input != string.Empty
    Main_p0 -[#grey]> Console_Write_a0 : ("Rechenoperation [Enter...Exit]:  ")
    Main_p0 -[#grey]> Console_ReadLine
    Console_ReadLine -[#blue]-> Main_p0 : input
    alt#LightBlue input != string.Empty
        Main_p0 -[#grey]> Parse_a0 : (input)
        Parse_a0 -[#blue]-> Main_p0 : result
        Main_p0 -[#grey]> Console_WriteLine_a0 : ($"{input} = {result}")
    end
end
@enduml
