@startuml CompleteActivityDiagram
header
generated on 05.03.2024 11:15:19
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#LightBlue:int idx = 1
int number = 100;
:PrintLine("***************************************");
:PrintLine("* Ausgabe für Fizz-Buzz von 1 bis 100 *");
:PrintLine("* Fizz, wenn durch 3 teilbar ist      *");
:PrintLine("* Buzz, wenn durch 5 teilbar ist      *");
:PrintLine("***************************************");
while (idx <= number) is (<color:green>yes)
    if (idx % 3 != 0 && idx % 5 != 0) then (<color:green>yes)
        :Print($"{idx} ");
    endif
    if (idx % 3 == 0) then (<color:green>yes)
        :Print("Fizz ");
    endif
    if (idx % 5 == 0) then (<color:green>yes)
        :Print("Buzz ");
    endif
    if (idx % 5 == 0 && idx % 3 == 0) then (<color:green>yes)
        :Print("Fizz Buzz ");
    endif
    :idx++;
endwhile (<color:red>no)
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
