@startuml object
object Heap_54181145#LightBlue {
  _size => 1000
  _first => 64062224
}
object Block_64062224#LightGoldenRodYellow {
  _address => 0
  _size => 100
  _next => 3129430
}
object Block_3129430#LightGoldenRodYellow {
  _address => 100
  _size => 200
  _next => null
}
Block_64062224::_next --> Block_3129430
Heap_54181145::_first --> Block_64062224
@enduml
