@startuml object
object Heap_3908350#LightBlue {
  _size => 1000
  _first => 14966502
}
object Block_14966502#LightGoldenRodYellow {
  _address => 0
  _size => 100
  _next => 45861094
}
object Block_45861094#LightGoldenRodYellow {
  _address => 100
  _size => 200
  _next => null
}
Block_14966502::_next --> Block_45861094
Heap_3908350::_first --> Block_14966502
@enduml
