@startuml object
object Heap_28726945#LightBlue {
  _size => 1000
  _first => 66394946
}
object Block_66394946#LightGoldenRodYellow {
  _address => 0
  _size => 100
  _next => 52116595
}
object Block_52116595#LightGoldenRodYellow {
  _address => 100
  _size => 200
  _next => 20706689
}
object Block_20706689#LightGoldenRodYellow {
  _address => 300
  _size => 300
  _next => null
}
Block_52116595::_next --> Block_20706689
Block_66394946::_next --> Block_52116595
Heap_28726945::_first --> Block_66394946
@enduml
