@startuml object
object Heap_16118003#LightBlue {
  _size => 1000
  _first => 2933762
}
object Block_2933762#LightGoldenRodYellow {
  _address => 0
  _size => 100
  _next => 61609009
}
object Block_61609009#LightGoldenRodYellow {
  _address => 100
  _size => 200
  _next => null
}
Block_2933762::_next --> Block_61609009
Heap_16118003::_first --> Block_2933762
@enduml
