@startuml object
object Heap_32561327#LightBlue {
  _size => 1000
  _first => 30330347
}
object Block_30330347#LightGoldenRodYellow {
  _address => 0
  _size => 50
  _next => 32957531
}
object Block_32957531#LightGoldenRodYellow {
  _address => 50
  _size => 25
  _next => 21019525
}
object Block_21019525#LightGoldenRodYellow {
  _address => 75
  _size => 20
  _next => 38756850
}
object Block_38756850#LightGoldenRodYellow {
  _address => 95
  _size => 5
  _next => 65357506
}
object Block_65357506#LightGoldenRodYellow {
  _address => 100
  _size => 200
  _next => null
}
Block_38756850::_next --> Block_65357506
Block_21019525::_next --> Block_38756850
Block_32957531::_next --> Block_21019525
Block_30330347::_next --> Block_32957531
Heap_32561327::_first --> Block_30330347
@enduml
