@startuml object
object Heap_33819242#LightBlue {
  _size => 1000
  _first => 16118003
}
object Block_16118003#LightGoldenRodYellow {
  _address => 100
  _size => 200
  _next => null
}
Heap_33819242::_first --> Block_16118003
@enduml
