@startuml object
object Heap_33819242#LightBlue {
  _size => 100
  _first => 39115446
}
object Block_39115446#LightGoldenRodYellow {
  _address => 0
  _size => 100
  _next => null
}
Heap_33819242::_first --> Block_39115446
@enduml
