@startuml object
object Heap_21337957#LightBlue {
  _size => 1000
  _first => 42331837
}
object Block_42331837#LightGoldenRodYellow {
  _address => 0
  _size => 50
  _next => null
}
Heap_21337957::_first --> Block_42331837
@enduml
