@startuml object
object Heap_33819242#LightBlue {
  _size => 1000
  _first => 16118003
}
object Block_16118003#LightGoldenRodYellow {
  _address => 100
  _size => 200
  _next => 2933762
}
object Block_2933762#LightGoldenRodYellow {
  _address => 300
  _size => 300
  _next => null
}
Block_16118003::_next --> Block_2933762
Heap_33819242::_first --> Block_16118003
@enduml
