@startuml object
object Heap_57592306#LightBlue {
  _size => 1000
  _first => 1478876
}
object Block_1478876#LightGoldenRodYellow {
  _address => 0
  _size => 100
  _next => 48204678
}
object Block_48204678#LightGoldenRodYellow {
  _address => 100
  _size => 150
  _next => null
}
Block_1478876::_next --> Block_48204678
Heap_57592306::_first --> Block_1478876
@enduml
