@startuml object
object Heap_16553355#LightBlue {
  _size => 1000
  _first => 12076145
}
object Block_12076145#LightGoldenRodYellow {
  _address => 0
  _size => 100
  _next => 52272470
}
object Block_52272470#LightGoldenRodYellow {
  _address => 100
  _size => 200
  _next => null
}
Block_12076145::_next --> Block_52272470
Heap_16553355::_first --> Block_12076145
@enduml
