@startuml object
object Heap_14798442#LightBlue {
  _size => 1000
  _first => 42331837
}
object Block_42331837#LightGoldenRodYellow {
  _address => 0
  _size => 20
  _next => 16553355
}
object Block_16553355#LightGoldenRodYellow {
  _address => 20
  _size => 20
  _next => 52272470
}
object Block_52272470#LightGoldenRodYellow {
  _address => 60
  _size => 20
  _next => null
}
Block_16553355::_next --> Block_52272470
Block_42331837::_next --> Block_16553355
Heap_14798442::_first --> Block_42331837
@enduml
