@startuml object
object Heap_32561327#LightBlue {
  _size => 1000
  _first => 12699242
}
object Block_12699242#LightGoldenRodYellow {
  _address => 0
  _size => 100
  _next => 65357506
}
object Block_65357506#LightGoldenRodYellow {
  _address => 100
  _size => 200
  _next => null
}
Block_12699242::_next --> Block_65357506
Heap_32561327::_first --> Block_12699242
@enduml
