@startuml object
object Heap_21337957#LightBlue {
  _size => 1000
  _first => 45443930
}
object Block_45443930#LightGoldenRodYellow {
  _address => 0
  _size => 100
  _next => null
}
Heap_21337957::_first --> Block_45443930
@enduml
