@startuml Node
title Node
class Node #GhostWhite {
- double _value
- Node? _prev
- Node? _next
---
+ double getValue()
+ Void setValue(double value)
+ Node? getPrev()
+ Void setPrev(Node? value)
+ Node? getNext()
+ Void setNext(Node? value)
---
}
Node "0..1" *-- "1" Node : _prev
Node "0..1" *-- "1" Node : _next
@enduml
