@startuml ObjectDiagram.Generate
title ObjectDiagram.Generate
participant "Generate(params object[] items)" as Generate_p0 #LightYellow
participant "DiagramCreator.CreateObjectDiagram(100,items).ToList()" as DiagramCreator_CreateObjectDiagram_100_items_ToList #LightGreen
participant "diagramData.Insert(a0,a1)" as diagramData_Insert_a0_a1 #LightGreen
participant "diagramData.Add(a0)" as diagramData_Add_a0 #LightGreen
participant "Path.Exists(a0)" as Path_Exists_a0 #LightGreen
participant "Directory.CreateDirectory(a0)" as Directory_CreateDirectory_a0 #LightGreen
participant "File.WriteAllLines(a0,a1)" as File_WriteAllLines_a0_a1 #LightGreen
autonumber
Generate_p0 -[#grey]> DiagramCreator_CreateObjectDiagram_100_items_ToList
DiagramCreator_CreateObjectDiagram_100_items_ToList -[#blue]-> Generate_p0 : diagramData
Generate_p0 -[#grey]> diagramData_Insert_a0_a1 : (0, "@start" + "uml stack")
Generate_p0 -[#grey]> diagramData_Insert_a0_a1 : (1, "title Object Diagram for LinkedList")
Generate_p0 -[#grey]> diagramData_Add_a0 : ("@end" + "uml")
alt#LightBlue Path.Exists(DiagramPath) == false
    Generate_p0 -[#grey]> Path_Exists_a0 : (DiagramPath)
    Generate_p0 -[#grey]> Directory_CreateDirectory_a0 : (DiagramPath)
end
Generate_p0 -[#grey]> File_WriteAllLines_a0_a1 : (FilePath, diagramData)
@enduml
