@startuml Program.Main
header
generated on 05.03.2024 11:15:19
end header
title Program.Main
start
#LightBlue:int payment = 0;
:PrintLine("Parkschein Automat");
:PrintLine("==================");
:PrintLine();
:PrintHeader();
:payment = ReadParkingPayment();
:PrintTicket(payment);
:PrintLine();
:PrintLine("Programm beenden mit Eingabetaste...");
:ReadLine();
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
