@startuml Program.PrintHeader
header
generated on 05.03.2024 11:15:19
end header
title Program.PrintHeader
start
:PrintLine($"Parkscheinautomat mit Mindestparkdauer {_minTimeInMinutes} Minuten und Höchstparkdauer {_maxTimeInMinutes} Minuten");
:PrintLine("Tarif pro Stunde: 1 Euro");
:PrintLine($"Zulässige Münzen: {string.Join(", ", _coins)} Cent");
:PrintLine("Parkschein drucken mit d oder D");
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
