@startuml Program.ToMinutes
header
generated on 3/9/2024 8:21:55 PM
end header
title Program.ToMinutes
start
#Lavender:return (int)(_costPerMinute * throwInCents);
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
