@startuml Program.PrintTicket
header
generated on 05.03.2024 11:15:19
end header
title Program.PrintTicket
start
:PrintLine("Ticket ausgeben:");
if (paymentInCents > _maxPaymentInCents) then (<color:green>yes)
    :PrintLine($"Danke für Ihre Spende von {paymentInCents - _maxPaymentInCents} Cent");
endif
#LightBlue:int minutes = ToMinutes(Math.Min(paymentInCents, _maxPaymentInCents));
:PrintLine($"Sie dürfen {ToHoursFormat(minutes)} Stunden parken");
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
