@startuml Program.PrintTicket
title Program.PrintTicket
start
#Lavender:Params(int paymentInCents);
:PrintLine("Ticket ausgeben:");
if (paymentInCents > _maxPaymentInCents) then (<color:green>yes)
    :PrintLine($"Danke für Ihre Spende von {paymentInCents - _maxPaymentInCents} Cent");
endif
#LightBlue:int minutes = ToMinutes(Math.Min(paymentInCents, _maxPaymentInCents));
:PrintLine($"Sie dürfen {ToHoursFormat(minutes)} Stunden parken");
stop
@enduml
