@startuml CompleteActivityDiagram
title CompleteActivityDiagram
start
note right:  Program.Main
#LightBlue:int payment = 0;
:PrintLine("Parkschein Automat");
:PrintLine("==================");
:PrintLine();
:PrintHeader();
:payment = ReadParkingPayment();
:PrintTicket(payment);
:PrintLine();
:PrintLine("Programm beenden mit Eingabetaste...");
:ReadLine();
stop
start
note right:  Program.ReadParkingPayment
#LightBlue:int result = 0
bool exit = false
string input;
repeat
    :Print($"Parkzeit bisher: {(result >= _minPaymentInCents ? ToHoursFormat(ToMinutes(result)) : "00:00")}, Einwurf bisher: {result} Cent,  d für Ticket, Einwurf in Cent: ");
    :input = ReadLine();
    if (input.ToLower() == "d") then (<color:green>yes)
        if (result < _minPaymentInCents) then (<color:green>yes)
            :Print($"Mindesteinwurf {_minPaymentInCents} Cent, bisher haben Sie {result} eingeworfen");
          else (<color:red>no)
              :exit = true;
        endif
      else (<color:red>no)
        if (int.TryParse(input, out int coin)) then (<color:green>yes)
            if (_coins.Contains(coin)) then (<color:green>yes)
                :result += coin;
              else (<color:red>no)
                  :PrintLine($"'{coin}' ist ein ungültiger Wert!");
            endif
        endif
    endif
repeat while (exit == false && result < _maxPaymentInCents) is (<color:green>yes)
stop
start
note right:  Program.PrintHeader
:PrintLine($"Parkscheinautomat mit Mindestparkdauer {_minTimeInMinutes} Minuten und Höchstparkdauer {_maxTimeInMinutes} Minuten");
:PrintLine("Tarif pro Stunde: 1 Euro");
:PrintLine($"Zulässige Münzen: {string.Join(", ", _coins)} Cent");
:PrintLine("Parkschein drucken mit d oder D");
stop
start
note right:  Program.PrintTicket
:PrintLine("Ticket ausgeben:");
if (paymentInCents > _maxPaymentInCents) then (<color:green>yes)
    :PrintLine($"Danke für Ihre Spende von {paymentInCents - _maxPaymentInCents} Cent");
endif
#LightBlue:int minutes = ToMinutes(Math.Min(paymentInCents, _maxPaymentInCents));
:PrintLine($"Sie dürfen {ToHoursFormat(minutes)} Stunden parken");
stop
@enduml
