@startuml Program.Main
title Program.Main
start
:int payment = 0;
:PrintLine("Parkschein Automat");
:PrintLine("==================");
:PrintLine();
:PrintHeader();
:payment = ReadParkingPayment();
:PrintTicket(payment);
:PrintLine();
:PrintLine("Programm beenden mit Eingabetaste...");
:ReadLine();
stop
@enduml
