@startuml Program.GetIncorrectTipps
title Program.GetIncorrectTipps
start
#LightGreen:Params(LotteryTip[] tipps);
#LightSkyBlue:List<LotteryTip> result = new List<LotteryTip>();
#LightSkyBlue:int i = 0;
while (i < tipps.Length) is (<color:green>yes)
        if (IsTipValid(tipps[i]) == false) then (<color:green>yes)
                #WhiteSmoke:result.Add(tipps[i]);
        endif
:i++;
endwhile (<color:red>no)
#Lavender:return result.ToArray();
stop
@enduml
