@startuml Program.CountNumberInTip
title Program.CountNumberInTip
start
#LightGreen:Params(int number,LotteryTip tip);
#LightSkyBlue:int result = 0;
#LightSkyBlue:int i = 0;
while (i < tip.Numbers.Length) is (<color:green>yes)
        if (number == tip.Numbers[i]) then (<color:green>yes)
                #WhiteSmoke:result++;
        endif
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
