@startuml Program.ReadTippsFromFile
title Program.ReadTippsFromFile
start
#LightGreen:Params(string filePath);
#LightSkyBlue:string[] lines = File.ReadAllLines(filePath)
LotteryTip[] tipps = new LotteryTip[lines.Length];
#LightSkyBlue:int i = 0;
while (i < lines.Length) is (<color:green>yes)
    #LightSkyBlue:LotteryTip tip = new LotteryTip();
    #LightSkyBlue:string[] parts = lines[i].Split(';');
    #WhiteSmoke:tip.Id = parts[0];
    #WhiteSmoke:tip.Numbers[0] = int.Parse(parts[1]);
    #WhiteSmoke:tip.Numbers[1] = int.Parse(parts[2]);
    #WhiteSmoke:tip.Numbers[2] = int.Parse(parts[3]);
    #WhiteSmoke:tip.Numbers[3] = int.Parse(parts[4]);
    #WhiteSmoke:tip.Numbers[4] = int.Parse(parts[5]);
    #WhiteSmoke:tip.Numbers[5] = int.Parse(parts[6]);
    #WhiteSmoke:tipps[i] = tip;
:i++;
endwhile (<color:red>no)
#Lavender:return tipps;
stop
@enduml
