@startuml Program.WriteTippsToFile
title Program.WriteTippsToFile
participant "WriteTippsToFile(LotteryTip[]tipps,stringfilePath)" as WriteTippsToFile_p0_p1 #LightYellow
participant "File.WriteAllLines(a0,a1)" as File_WriteAllLines_a0_a1 #LightGreen
autonumber
WriteTippsToFile_p0_p1 -[#grey]> File_WriteAllLines_a0_a1 : (filePath, lines)
@enduml
