@startuml Program.FibonacciRecursive
title Program.FibonacciRecursive
start
#LightGreen:Params(int n);
#LightYellow:if (n < 2) then (<color:green>yes)
        #Lavender:return n;
    else (<color:red>no)
            #Lavender:return FibonacciRecursive(n - 1) + FibonacciRecursive(n - 2);
endif
stop
@enduml
