@startuml Program.DisplayRacers
title Program.DisplayRacers
start
#LightGreen:Params(Racer[] racers);
#WhiteSmoke:PrintLine($"{"Nr",-7}{"Name",-25}{"JG",-5}{"Nation",-7}{"Team",-40}{"Zeit[sec]",-10}");
#LightSkyBlue:int i = 0;
while (i < racers.Length) is (<color:green>yes)
        #WhiteSmoke:PrintLine($"{racers[i].Number,-7}{racers[i].Name,-25}{racers[i].Vintage,-5}{racers[i].Nationality,-7}{racers[i].Team,-40}{racers[i].Time,-10:f2}");
:i++;
endwhile (<color:red>no)
stop
@enduml
