@startuml Program
title Program
 class Program #GhostWhite {
- {const} string FileName = "BusinessRun.csv"
---
---
- {static} void Main(string[] args)
- {static} Racer[] ReadRacersFromFile(string fileName)
- {static} void DisplayTheFirstThreeRacers(Racer[] racers)
+ {static} void SortRacerByTime(Racer[] racers)
- {static} double CalculateAverageTime(Racer[] racers)
- {static} double ConvertTimeToSeconds(string time)
- {static} bool IsValidTimeParts(string[] parts)
}
@enduml
