@startuml Program.FormatBinary
title Program.FormatBinary
start
#LightGreen:Params(string number,int wide);
#LightSkyBlue:string result = string.Empty\nint expandLength = wide - number.Length % wide + number.Length;
#WhiteSmoke:number = ExpandNumber(number, expandLength);
#LightSkyBlue:int i = 0;
while (i < number.Length) is (<color:green>yes)
        if (i > 0 && i % wide == 0) then (<color:green>yes)
                #WhiteSmoke:result += ' ';
        endif
        #WhiteSmoke:result += number[i];
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
