@startuml Program.FormatBinary
title Program.FormatBinary
start
#Lavender:Params(string number, int wide);
#LightBlue:string result = string.Empty
int expandLength = wide - number.Length % wide + number.Length;
:number = ExpandNumber(number, expandLength);
#LightBlue:int i = 0;
while (i < number.Length) is (<color:green>yes)
    if (i > 0 && i % wide == 0) then (<color:green>yes)
        :result += ' ';
    endif
    :result += number[i];
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
