@startuml Program.ExpandNumber
title Program.ExpandNumber
start
#LightGreen:Params(string number,int numberLength);
while (number.Length < numberLength) is (<color:green>yes)
        #WhiteSmoke:number = '0' + number;
endwhile (<color:red>no)
#Lavender:return number;
stop
@enduml
