@startuml Program.CheckBinaryNumber
title Program.CheckBinaryNumber
start
#LightGreen:Params(string number);
#LightSkyBlue:bool result = true\nint idx = 0;
while (idx < number.Length && result) is (<color:green>yes)
        #WhiteSmoke:result = IsBinaryDigit(number[idx++]);
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
