@startuml Program.FormatBinary
header
generated on 3/9/2024 6:07:23 PM
end header
title Program.FormatBinary
start
#LightBlue:string result = string.Empty
int expandLength = wide - number.Length % wide + number.Length;
:number = ExpandNumber(number, expandLength);
#LightBlue:int i = 0;
while (i < number.Length) is (<color:green>yes)
    if (i > 0 && i % wide == 0) then (<color:green>yes)
        :result += ' ';
    endif
    :result += number[i];
:i++;
endwhile (<color:red>no)
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
