@startuml Program.ReadBinaryNumber
header
generated on 3/9/2024 8:21:55 PM
end header
title Program.ReadBinaryNumber
start
#LightBlue:string result
bool validInput;
repeat
    :Print($"Geben Sie die {number}. Binärzahl ein: ");
    :result = ReadLine();
    :validInput = CheckBinaryNumber(result);
    if (!validInput) then (<color:green>yes)
        :PrintLine("Fehler: In einer Binärzahl sind nur 1 und 0 erlaubt!");
    endif
repeat while (validInput == false) is (<color:green>yes)
#Lavender:return result;
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
