@startuml Program.ReadBinaryNumber
title Program.ReadBinaryNumber
start
#LightGreen:Params(int number);
#LightSkyBlue:string result
bool validInput;
repeat
        #WhiteSmoke:Print($"Geben Sie die {number}. Binärzahl ein: ");
        #WhiteSmoke:result = ReadLine();
        #WhiteSmoke:validInput = CheckBinaryNumber(result);
        if (!validInput) then (<color:green>yes)
                #WhiteSmoke:PrintLine("Fehler: In einer Binärzahl sind nur 1 und 0 erlaubt!");
        endif
repeat while (validInput == false) is (<color:green>yes)
#Lavender:return result;
stop
@enduml
