@startuml Program.FormatBinary
title Program.FormatBinary
start
:string result = string.Empty;
:int expandLength = wide - number.Length % wide + number.Length;
:number = ExpandNumber(number, expandLength);
:int i = 0;
while (i < number.Length) is (yes)
    if (i > 0 && i % wide == 0) then (yes)
        :result += ' ';
    endif
    :result += number[i];
:i++;
endwhile (no)
stop
@enduml
