@startuml Program.Main
title Program.Main
participant "Main(string[] args)" as Main_p0 #LightYellow
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
participant "ReadBinaryNumber(a0)" as ReadBinaryNumber_a0 #LightGreen
participant "AddBinaryNumbers(a0,a1)" as AddBinaryNumbers_a0_a1 #LightGreen
participant "Console.WriteLine()" as Console_WriteLine #LightGreen
participant "Console.ReadLine()" as Console_ReadLine #LightGreen
autonumber
Main_p0 -> Console_WriteLine_a0 : ("Binäraddierer")
Main_p0 -> Console_WriteLine_a0 : ("=============")
Main_p0 -> ReadBinaryNumber_a0 : (1)
ReadBinaryNumber_a0 --> Main_p0 : result
Main_p0 -> ReadBinaryNumber_a0 : (2)
ReadBinaryNumber_a0 --> Main_p0 : result
Main_p0 -> AddBinaryNumbers_a0_a1 : (number1, number2)
AddBinaryNumbers_a0_a1 --> Main_p0 : result
Main_p0 -> Console_WriteLine_a0 : ($"{FormatBinary(number1, 8)} + {FormatBinary(number2, 8)} =  {FormatBinary(result, 8)}")
Main_p0 -> Console_WriteLine
Main_p0 -> Console_WriteLine_a0 : ("Beenden mit Eingabetaste... ")
Main_p0 -> Console_ReadLine
@enduml
