@startuml Program.CheckBinaryNumber
title Program.CheckBinaryNumber
participant "CheckBinaryNumber(stringnumber)" as CheckBinaryNumber_p0 #LightYellow
participant "IsBinaryDigit(a0)" as IsBinaryDigit_a0 #LightGreen
autonumber
loop idx < number.Length && result
    CheckBinaryNumber_p0 -> IsBinaryDigit_a0 : (number[idx++])
    IsBinaryDigit_a0 --> CheckBinaryNumber_p0 : result
end
@enduml
