@startuml Program.ReadPosturePoints
header
generated on 3/9/2024 8:21:55 PM
end header
title Program.ReadPosturePoints
start
#LightBlue:int idx = 0
string input
double[] result = new double[count];
while (idx < count) is (<color:green>yes)
    :Print($"Wertungsrichter {idx + 1} [0-20]: ");
    :input = ReadLine();
    if (double.TryParse(input, out result[idx]) 
                    && result[idx] >= 0 
                    && result[idx] <= 20 
                    && (result[idx] % 1 == 0 || result[idx] % 1 == 0.5)) then (<color:green>yes)
        :idx++;
      else (<color:red>no)
          :PrintLine("Ungültige Eingabe!");
    endif
endwhile (<color:red>no)
#Lavender:return result;
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
