@startuml Program.ReadJumpFar
title Program.ReadJumpFar
start
#LightBlue:double result
string input
bool valid = false;
repeat
    :Print($"Weite in Meter [0-200]: ");
    :input = ReadLine();
    if (double.TryParse(input, out result) && result >= 0 && result <= 200) then (<color:green>yes)
        :valid = true;
      else (<color:red>no)
          :PrintLine("Ungültige Eingabe!");
    endif
repeat while (valid == false) is (<color:green>yes)
#Lavender:return result;
stop
@enduml
