@startuml Program.Main
title Program.Main
start
#Lavender:Params(string[] args);
#LightBlue:double far, points
double[] posturePoints;
:PrintLine("Notenermittlung für Skispringer");
:PrintLine("===============================");
:far = ReadJumpFar();
:PrintLine();
:posturePoints = ReadPosturePoints(5);
:points = CalculateJump(far) + CalculatePosturePoints(posturePoints);
:PrintLine();
:PrintLine($"Weitenpunkte: {CalculateJump(far):f} Haltungsnote: {CalculatePosturePoints(posturePoints):f} Gesamt: {points:f}");
:PrintLine();
:PrintLine("Beenden mit Eingabetaste... ");
:ReadLine();
stop
@enduml
