@startuml Program.ReadJumpFar
title Program.ReadJumpFar
start
:double result;
:string input;
:bool valid = false;
repeat
    :Print($"Weite in Meter [0-200]: ");
    :input = ReadLine();
    if (double.TryParse(input, out result) && result >= 0 && result <= 200) then (yes)
        :valid = true;
      else (no)
          :PrintLine("Ungültige Eingabe!");
    endif
repeat while (valid == false) is (yes)
stop
@enduml
