@startuml Program.Main
title Program.Main
participant "Main(string[]args)" as Main_p0 #LightYellow
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
participant "ReadJumpFar()" as ReadJumpFar #LightGreen
participant "Console.WriteLine()" as Console_WriteLine #LightGreen
participant "ReadPosturePoints(a0)" as ReadPosturePoints_a0 #LightGreen
participant "Console.ReadLine()" as Console_ReadLine #LightGreen
autonumber
Main_p0 -[#grey]> Console_WriteLine_a0 : ("Notenermittlung für Skispringer")
Main_p0 -[#grey]> Console_WriteLine_a0 : ("===============================")
Main_p0 -[#grey]> ReadJumpFar
ReadJumpFar -[#blue]-> Main_p0 : far
Main_p0 -[#grey]> Console_WriteLine
Main_p0 -[#grey]> ReadPosturePoints_a0 : (5)
ReadPosturePoints_a0 -[#blue]-> Main_p0 : posturePoints
Main_p0 -[#grey]> Console_WriteLine
Main_p0 -[#grey]> Console_WriteLine_a0 : ($"Weitenpunkte: {CalculateJump(far):f} Haltungsnote: {CalculatePosturePoints(posturePoints):f} Gesamt: {points:f}")
Main_p0 -[#grey]> Console_WriteLine
Main_p0 -[#grey]> Console_WriteLine_a0 : ("Beenden mit Eingabetaste... ")
Main_p0 -[#grey]> Console_ReadLine
@enduml
