@startuml CompleteActivityDiagram
header
generated on 3/9/2024 7:37:48 PM
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#LightBlue:string input, cardNumber = string.Empty
int idx
int sum = 0
int digit, diff
int evenSum = 0, oddSum = 0
bool valid = true;
:PrintLine("***************************************************");
:PrintLine("* Kreditkarten-Prüfer                             *");
:PrintLine("***************************************************");
:PrintLine();
:Print("Geben Sie Ihre 16-stellige Kreditkartennummer ein: ");
:input = ReadLine();
#LightBlue:int i = 0;
while (i < input.Length) is (<color:green>yes)
    if (char.IsWhiteSpace(input[i]) == false) then (<color:green>yes)
        :cardNumber += input[i];
    endif
:i++;
endwhile (<color:red>no)
:valid = cardNumber.Length == 16;
:idx = 0;
while (valid && idx < cardNumber.Length) is (<color:green>yes)
    :valid = char.IsDigit(cardNumber[idx++]);
endwhile (<color:red>no)
:idx = 0;
while (valid && idx < cardNumber.Length - 1) is (<color:green>yes)
    :digit = (cardNumber[idx] - '0') * 2;
    :evenSum = digit > 9 ? evenSum + digit % 10 + (digit / 10 % 10)
                                    : evenSum + digit;
    :idx = idx + 2;
endwhile (<color:red>no)
:idx = 1;
while (valid && idx < cardNumber.Length - 1) is (<color:green>yes)
    :oddSum = oddSum + (cardNumber[idx] - '0');
    :idx = idx + 2;
endwhile (<color:red>no)
if (valid) then (<color:green>yes)
    :sum = evenSum + oddSum;
    :diff = (10 - sum % 10) % 10;
    :valid = diff == cardNumber[cardNumber.Length - 1] - '0';
endif
:PrintLine();
if (valid) then (<color:green>yes)
    :PrintLine($"Die Kreditkartennummer '{input}' ist gültig.");
  else (<color:red>no)
      :PrintLine($"Die Kreditkartennummer '{input}' ist ungültig.");
endif
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
