@startuml CompleteActivityDiagram
header
generated on 12.03.2024 22:57:23
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#Lavender:Params(string[] args);
#LightBlue:string input, output = string.Empty;
:PrintLine("***************************************************");
:PrintLine("* Vocal Filter                                    *");
:PrintLine("***************************************************");
:PrintLine();
:Print("Eingabetext: ");
:input = ReadLine();
#LightBlue:int i = 0;
while (i < input.Length) is (<color:green>yes)
    #LightBlue:char chr = char.ToLower(input[i]);
    if (chr == 'a' || chr == 'e' || chr == 'i' || chr == 'o' || chr == 'u') then (<color:green>yes)
        if (output.Contains(input[i]) == false) then (<color:green>yes)
            :output += input[i];
        endif
    endif
:i++;
endwhile (<color:red>no)
:PrintLine($"Ausgabetext: {output}");
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
