@startuml CompleteActivityDiagram
header
generated on 09/04/2024 14:47:12
end header
title CompleteActivityDiagram
start
note right:  Program.Main
#LightGreen:Params(string[] args);
#LightSkyBlue:string input, output = string.Empty;
#WhiteSmoke:PrintLine("***************************************************");
#WhiteSmoke:PrintLine("* Vocal Filter                                    *");
#WhiteSmoke:PrintLine("***************************************************");
#WhiteSmoke:PrintLine();
#WhiteSmoke:Print("Eingabetext: ");
#WhiteSmoke:input = ReadLine();
#LightSkyBlue:int i = 0;
while (i < input.Length) is (<color:green>yes)
        #LightSkyBlue:char chr = char.ToLower(input[i]);
        if (chr == 'a' || chr == 'e' || chr == 'i' || chr == 'o' || chr == 'u') then (<color:green>yes)
                if (output.Contains(input[i]) == false) then (<color:green>yes)
                        #WhiteSmoke:output += input[i];
                endif
        endif
:i++;
endwhile (<color:red>no)
#WhiteSmoke:PrintLine($"Ausgabetext: {output}");
#WhiteSmoke:PrintLine();
#WhiteSmoke:PrintLine("Press any key to exit: ");
#WhiteSmoke:ReadKey();
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
