@startuml Program.Main
title Program.Main
participant "Main(string[]args)" as Main_p0 #LightYellow
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
participant "Console.WriteLine()" as Console_WriteLine #LightGreen
participant "Console.Write(a0)" as Console_Write_a0 #LightGreen
participant "Console.ReadLine()" as Console_ReadLine #LightGreen
participant "char.ToLower(a0)" as char_ToLower_a0 #LightGreen
participant "output.Contains(a0)" as output_Contains_a0 #LightGreen
participant "Console.ReadKey()" as Console_ReadKey #LightGreen
autonumber
Main_p0 -[#grey]> Console_WriteLine_a0 : ("***************************************************")
Main_p0 -[#grey]> Console_WriteLine_a0 : ("* Vocal Filter                                    *")
Main_p0 -[#grey]> Console_WriteLine_a0 : ("***************************************************")
Main_p0 -[#grey]> Console_WriteLine
Main_p0 -[#grey]> Console_Write_a0 : ("Eingabetext: ")
Main_p0 -[#grey]> Console_ReadLine
Console_ReadLine -[#blue]-> Main_p0 : input
Main_p0 -[#grey]> char_ToLower_a0 : (input[i])
char_ToLower_a0 -[#blue]-> Main_p0 : chr
Main_p0 -[#grey]> output_Contains_a0 : (input[i])
output_Contains_a0 -[#blue]-> Main_p0 : result
Main_p0 -[#grey]> Console_WriteLine_a0 : ($"Ausgabetext: {output}")
Main_p0 -[#grey]> Console_WriteLine
Main_p0 -[#grey]> Console_WriteLine_a0 : ("Press any key to exit: ")
Main_p0 -[#grey]> Console_ReadKey
@enduml
