@startuml Program.Main
title Program.Main
start
:PrintLine("Umrechnung Celsius  ->  Fahrenheit");
:PrintLine("==================================");
:PrintLine();
:Print("Eingabe Grad Celsius: ");
:input = ReadLine();
:celsius = Convert.ToDouble(input);
:fahrenheit = (celsius * 9.0 / 5.0) + 32;
:Print("Das Ergebnis: ");
if (fahrenheit >= 0) then (yes)
    :Print("Ist größer oder gleich 0", 10);
  else (no)
      :Print("Ist kleiner 0", 10);
endif
:PrintLine();
:PrintLine($"Celsius:    {celsius:f1}");
:PrintLine($"Fahrenheit: {fahrenheit:f1}");
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
@enduml
