@startuml Program.Main
title Program.Main
start
:PrintLine("MinMax Calculator");
:PrintLine("=================");
:PrintLine();
:Print("Eingabe Zahl 1: ");
:input = ReadLine();
:nOne = Convert.ToInt32(input);
:Print("Eingabe Zahl 2: ");
:input = ReadLine();
:nTwo = Convert.ToInt32(input);
:Print("Eingabe Zahl 3: ");
:input = ReadLine();
:nThree = Convert.ToInt32(input);
if (nOne >= nTwo && nTwo >= nThree) then (yes)
    :nMax = nOne;
  else (no)
    if (nTwo >= nOne && nOne >= nThree) then (yes)
        :nMax = nTwo;
      else (no)
          :nMax = nThree;
    endif
endif
if (nOne <= nTwo && nTwo <= nThree) then (yes)
    :nMin = nOne;
  else (no)
    if (nTwo <= nOne && nOne <= nThree) then (yes)
        :nMin = nTwo;
      else (no)
          :nMin = nThree;
    endif
endif
:PrintLine();
:PrintLine($"Max = {nMax, 10}");
:PrintLine($"Min = {nMin, 10}");
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
@enduml
