@startuml CompleteActivityDiagram
title CompleteActivityDiagram
start
note right:  Program.Main
:PrintLine("Das große Rätsel von Dagobert!");
:PrintLine("==============================");
:PrintLine();
#LightBlue:int UPPER_RANGE = 2_000_000
int LOWER_RANGE = 1_000_000
int tSum, t = 1_000, qSum, q = 1_000;
repeat
    :tSum = (t + 1) * t / 2;
    :qSum = q * q;
    if (tSum < qSum) then (<color:green>yes)
        :t++;
      else (<color:red>no)
        if (qSum < tSum) then (<color:green>yes)
            :q++;
        endif
    endif
repeat while (tSum != qSum && tSum <= UPPER_RANGE) is (<color:green>yes)
if (tSum == qSum) then (<color:green>yes)
    :PrintLine();
    :PrintLine($"Die Lösung des Rätsels [{t},{q}]: Es sind {qSum} Dukaten!");
  else (<color:red>no)
      :PrintLine();
      :PrintLine($"Es gibt keine Dreieckszahl und Quadratzahl welche im Bereich {LOWER_RANGE} - {UPPER_RANGE} gleich sind!");
endif
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
@enduml
