@startuml Program.Main
title Program.Main
start
:string input;
:int number, operand, result;
:PrintLine("Pyramid of Numbres");
:PrintLine("==================");
:PrintLine();
:Print("Please enter a number: ");
:input = ReadLine();
:number = Convert.ToInt32(input);
:operand = number;
:PrintLine();
:int i = 2;
while (i < 10) is (yes)
    :result = operand * i;
    :PrintLine($"{operand} * {i} = {result}");
    :operand = result;
:i++;
endwhile (no)
:int i = 2;
while (i < 10) is (yes)
    :result = operand / i;
    :PrintLine($"{operand} / {i} = {result}");
    :operand = result;
:i++;
endwhile (no)
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
@enduml
