@startuml Program.SimulateRace
title Program.SimulateRace
start
#LightGreen:Params(Horse[] horses);
#LightSkyBlue:bool raceFinished = false;
#LightSkyBlue:int i = 0;
while (i < horses.Length) is (<color:green>yes)
        #WhiteSmoke:horses[i].Position = 0;
:i++;
endwhile (<color:red>no)
while (raceFinished == false) is (<color:green>yes)
        #LightSkyBlue:int i = 0;
        while (i < horses.Length) is (<color:green>yes)
                #LightSkyBlue:bool canMove = Random.Shared.Next(0, 2) == 1;
                if (canMove) then (<color:green>yes)
                        #WhiteSmoke:horses[i].Position++;
                        #WhiteSmoke:raceFinished = horses[i].Position >= 60;
                endif
        :i++;
        endwhile (<color:red>no)
        #WhiteSmoke:PrintSimulation(horses);
        #WhiteSmoke:Thread.Sleep(100);
endwhile (<color:red>no)
stop
@enduml
