@startuml Program.Main
title Program.Main
participant "Main(string[]args)" as Main_p0 #LightYellow
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
participant "Console.WriteLine()" as Console_WriteLine #LightGreen
participant "Console.Write(a0)" as Console_Write_a0 #LightGreen
participant "Console.ReadLine()" as Console_ReadLine #LightGreen
participant "char.IsDigit(a0)" as char_IsDigit_a0 #LightGreen
participant "Console.ReadKey()" as Console_ReadKey #LightGreen
autonumber
Main_p0 -> Console_WriteLine_a0 : ("***************************************************")
Main_p0 -> Console_WriteLine_a0 : ("* Digit Filter                                    *")
Main_p0 -> Console_WriteLine_a0 : ("***************************************************")
Main_p0 -> Console_WriteLine
Main_p0 -> Console_Write_a0 : ("Eingabetext: ")
Main_p0 -> Console_ReadLine
Console_ReadLine --> Main_p0 : input
loop i < input.Length
    alt char.IsDigit(input[i])
        Main_p0 -> char_IsDigit_a0 : (input[i])
        char_IsDigit_a0 --> Main_p0 : result
    end
end
Main_p0 -> Console_WriteLine_a0 : ($"Ausgabetext: {output}")
Main_p0 -> Console_WriteLine
Main_p0 -> Console_WriteLine_a0 : ("Press any key to exit: ")
Main_p0 -> Console_ReadKey
@enduml
