@startuml Program.Main
title Program.Main
start
:PrintLine();
:PrintLine("**********************************");
:PrintLine("         CASH MASHINE             ");
:PrintLine("**********************************");
repeat
    :PrintLine();
    :Print("Bitte geben Sie ihren 4 stelligen PIN-Code ein: ");
    :input = ReadLine();
    :userPin = Convert.ToInt32(input);
    if (userPin != DEFINED_PIN) then (yes)
        :userPinCorrect = false;
        :numberOfInvalidPins++;
        :PrintLine($"Sie haben {numberOfInvalidPins} mal einen falschen PIN eingegeben.");
      else (no)
          :userPinCorrect = true;
          :numberOfInvalidPins = 0;
    endif
repeat while (numberOfInvalidPins < MAX_INCORRECT_ENTRIES && userPinCorrect == false) is (yes)
if (numberOfInvalidPins >= MAX_INCORRECT_ENTRIES) then (yes)
    :PrintLine();
    :PrintLine("Sie haben Ihren PIN zu oft eingegeben!");
    :PrintLine(" => Ihre Karte wird eingezogen!");
  else (no)
    if (userPinCorrect) then (yes)
        :PrintLine($"Ihr Kontostand:                 {userBalance} EUR");
        :PrintLine($"Ihr Überziehungsrahmen:         {COVER_FRAME} EUR");
        :PrintLine("-----------------------------------------------------");
        :PrintLine($"maximaler Betrag                {maxAmount} EUR");
        :PrintLine();
        :Print("Geben Sie den Betrag ein, den Sie abheben wollen: ");
        :input = ReadLine();
        :amount = Convert.ToInt32(input);
        if (amount <= 0 || amount > maxAmount) then (yes)
            :PrintLine("Ungültiger Betrag - bitte versuchen Sie es erneut!");
            :PrintLine();
            :Print("Geben Sie den Betrag ein, den Sie abheben wollen: ");
            :input = ReadLine();
            :amount = Convert.ToInt32(input);
        endif
        if (amount > 0 && amount <= maxAmount) then (yes)
            :Print($"Soll der Betrag {amount:f2} EUR abgehoben werden [j/n]?: ");
            :input = ReadLine();
            if (input.ToLower() == "j") then (yes)
                :userBalance = userBalance - amount;
                :PrintLine($"Auszahlung des Betrages {amount:f2} EUR");
                :PrintLine($"Ihr neuer Kontostand: {userBalance:f2} EUR");
            endif
          else (no)
              :PrintLine("Die Abhebung wurde ohne Auszahlung beendet!");
        endif
    endif
endif
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
@enduml
