@startuml Program.PrintArray
header
generated on 05.03.2024 11:15:20
end header
title Program.PrintArray
start
#LightBlue:int i = 0;
while (i < array.Length) is (<color:green>yes)
    if (i > 0) then (<color:green>yes)
        :Print(" ");
    endif
    :Print(array[i]);
:i++;
endwhile (<color:red>no)
:PrintLine();
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
