@startuml Program.CreateRandomArray
header
generated on 05.03.2024 11:15:20
end header
title Program.CreateRandomArray
start
#LightBlue:int[] result = new int[size];
#LightBlue:int i = 0;
while (i < result.Length) is (<color:green>yes)
    :result[i] = Random.Shared.Next(min, max);
:i++;
endwhile (<color:red>no)
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
