@startuml Program.PrintArray
title Program.PrintArray
start
#Lavender:Params(int[] array);
#LightBlue:int i = 0;
while (i < array.Length) is (<color:green>yes)
    if (i > 0) then (<color:green>yes)
        :Print(" ");
    endif
    :Print(array[i]);
:i++;
endwhile (<color:red>no)
:PrintLine();
stop
@enduml
