@startuml Program.CreateRandomArray
title Program.CreateRandomArray
start
#Lavender:Params(int size, int min, int max);
#LightBlue:int[] result = new int[size];
#LightBlue:int i = 0;
while (i < result.Length) is (<color:green>yes)
    :result[i] = Random.Shared.Next(min, max);
:i++;
endwhile (<color:red>no)
#Lavender:return result;
stop
@enduml
