@startuml Program.PrintArray
title Program.PrintArray
start
#LightGreen:Params(int[] array);
while (i < array.Length) is (<color:green>yes)
        #LightYellow:if (i > 0) then (<color:green>yes)
                #WhiteSmoke:Print(" ");
        endif
        #WhiteSmoke:Print(array[i]);
:i++;
endwhile (<color:red>no)
#WhiteSmoke:PrintLine();
stop
@enduml
