@startuml Sort.SelectionSort
header
generated on 3/9/2024 8:21:55 PM
end header
title Sort.SelectionSort
start
#LightBlue:int i = 0;
while (i < array.Length - 1) is (<color:green>yes)
    #LightBlue:int minIdx = i;
    #LightBlue:int j = i + 1;
    while (j < array.Length) is (<color:green>yes)
        if (array[j] < array[minIdx]) then (<color:green>yes)
            :minIdx = j;
        endif
    :j++;
    endwhile (<color:red>no)
    if (minIdx != i) then (<color:green>yes)
        :Swap(ref array[i], ref array[minIdx]);
    endif
:i++;
endwhile (<color:red>no)
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
