@startuml Sort.InsertionSort
header
generated on 3/9/2024 8:21:55 PM
end header
title Sort.InsertionSort
start
#LightBlue:int i = 1;
while (i < array.Length) is (<color:green>yes)
    #LightBlue:int j = i;
    #LightBlue:int current = array[i];
    while (j > 0 && array[j - 1] > current) is (<color:green>yes)
        :array[j] = array[j - 1];
        :j--;
    endwhile (<color:red>no)
    :array[j] = current;
:i++;
endwhile (<color:red>no)
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
@enduml
