@startuml Sort.InsertionSort
title Sort.InsertionSort
start
#LightGreen:Params(int[] array);
while (i < array.Length) is (<color:green>yes)
        while (j > 0 && array[j - 1] > current) is (<color:green>yes)
                #WhiteSmoke:array[j] = array[j - 1];
                #WhiteSmoke:j--;
        endwhile (<color:red>no)
        #WhiteSmoke:array[j] = current;
:i++;
endwhile (<color:red>no)
stop
@enduml
