@startuml Sort.BubbleSort
title Sort.BubbleSort
start
#LightBlue:bool exchange
int length = array.Length;
repeat
    :exchange = false;
    #LightBlue:int i = 0;
    while (i < length - 1) is (<color:green>yes)
        if (array[i] > array[i + 1]) then (<color:green>yes)
            :Swap(ref array[i], ref array[i + 1]);
            :exchange = true;
        endif
    :i++;
    endwhile (<color:red>no)
    :length--;
repeat while (exchange) is (<color:green>yes)
stop
@enduml
