@startuml Sort.BubbleSort
title Sort.BubbleSort
start
#LightGreen:Params(int[] array);
#LightSkyBlue:bool exchange\nint length = array.Length;
repeat
        #WhiteSmoke:exchange = false;
        while (i < length - 1) is (<color:green>yes)
                #LightYellow:if (array[i] > array[i + 1]) then (<color:green>yes)
                        #WhiteSmoke:Swap(ref array[i], ref array[i + 1]);
                        #WhiteSmoke:exchange = true;
                endif
        :i++;
        endwhile (<color:red>no)
        #WhiteSmoke:length--;
repeat while (exchange) is (<color:green>yes)
stop
@enduml
