@startuml Sort.SelectionSort
title Sort.SelectionSort
start
#LightGreen:Params(int[] array);
while (i < array.Length - 1) is (<color:green>yes)
        while (j < array.Length) is (<color:green>yes)
                #LightYellow:if (array[j] < array[minIdx]) then (<color:green>yes)
                        #WhiteSmoke:minIdx = j;
                endif
        :j++;
        endwhile (<color:red>no)
        #LightYellow:if (minIdx != i) then (<color:green>yes)
                #WhiteSmoke:Swap(ref array[i], ref array[minIdx]);
        endif
:i++;
endwhile (<color:red>no)
stop
@enduml
