@startuml Program
title Program
 class Program #GhostWhite {
---
---
- {static} void Main(string[] args)
- {static} void PrintArray(string title, int[] array)
- {static} void PrintArray(int[] array)
- {static} int[] CreateRandomArray(int size)
- {static} int[] CreateRandomArray(int size, int min, int max)
}
@enduml
