@startuml CompleteActivityDiagram
header
generated on 3/9/2024 8:21:55 PM
end header
title CompleteActivityDiagram
start
note right:  Sort.BruteForceSort
#LightBlue:int i = 0;
while (i < array.Length) is (<color:green>yes)
    #LightBlue:int j = 0;
    while (j < array.Length - 1) is (<color:green>yes)
        if (array[j] > array[j + 1]) then (<color:green>yes)
            :Swap(ref array[j], ref array[j + 1]);
        endif
    :j++;
    endwhile (<color:red>no)
:i++;
endwhile (<color:red>no)
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
start
note right:  Sort.BubbleSort
#LightBlue:bool exchange
int length = array.Length;
repeat
    :exchange = false;
    #LightBlue:int i = 0;
    while (i < length - 1) is (<color:green>yes)
        if (array[i] > array[i + 1]) then (<color:green>yes)
            :Swap(ref array[i], ref array[i + 1]);
            :exchange = true;
        endif
    :i++;
    endwhile (<color:red>no)
    :length--;
repeat while (exchange) is (<color:green>yes)
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
start
note right:  Sort.InsertionSort
#LightBlue:int i = 1;
while (i < array.Length) is (<color:green>yes)
    #LightBlue:int j = i;
    #LightBlue:int current = array[i];
    while (j > 0 && array[j - 1] > current) is (<color:green>yes)
        :array[j] = array[j - 1];
        :j--;
    endwhile (<color:red>no)
    :array[j] = current;
:i++;
endwhile (<color:red>no)
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
start
note right:  Sort.SelectionSort
#LightBlue:int i = 0;
while (i < array.Length - 1) is (<color:green>yes)
    #LightBlue:int minIdx = i;
    #LightBlue:int j = i + 1;
    while (j < array.Length) is (<color:green>yes)
        if (array[j] < array[minIdx]) then (<color:green>yes)
            :minIdx = j;
        endif
    :j++;
    endwhile (<color:red>no)
    if (minIdx != i) then (<color:green>yes)
        :Swap(ref array[i], ref array[minIdx]);
    endif
:i++;
endwhile (<color:red>no)
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
start
note right:  Sort.Swap
#LightBlue:int tmp = v1;
:v1 = v2;
:v2 = tmp;
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
stop
footer
generated with the DiagramCreator by Prof.Gehrer
end footer
@enduml
