@startuml Program.PrintArray
title Program.PrintArray
participant "PrintArray(string title,int[] array)" as PrintArray_p0_p1 #LightYellow
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
participant "PrintArray(a0)" as PrintArray_a0 #LightGreen
autonumber
PrintArray_p0_p1 -[#grey]> Console_WriteLine_a0 : (title)
PrintArray_p0_p1 -[#grey]> PrintArray_a0 : (array)
@enduml
