@startuml Program.PrintArray
title Program.PrintArray
participant "PrintArray(int[]array)" as PrintArray_p0 #LightYellow
participant "Console.Write(a0)" as Console_Write_a0 #LightGreen
participant "Console.WriteLine()" as Console_WriteLine #LightGreen
autonumber
loop i < array.Length
    alt i > 0
        PrintArray_p0 -> Console_Write_a0 : (" ")
    end
    PrintArray_p0 -> Console_Write_a0 : (array[i])
end
PrintArray_p0 -> Console_WriteLine
@enduml
