@startuml Sort.BruteForceSort
title Sort.BruteForceSort
participant "Swap(a0,a1)" as Swap_a0_a1 #LightGreen
autonumber
loop i < array.Length
    loop j < array.Length - 1
        alt array[j] > array[j + 1]
            BruteForceSort_p0 -> Swap_a0_a1 : (ref array[j], ref array[j + 1])
        end
    end
end
@enduml
