@startuml Sort.BubbleSort
title Sort.BubbleSort
participant "BubbleSort(int[] array)" as BubbleSort_p0 #LightYellow
participant "Swap(a0,a1)" as Swap_a0_a1 #LightGreen
autonumber
loop#LightCoral exchange
    loop#LightCoral i < length - 1
        alt#LightBlue array[i] > array[i + 1]
            BubbleSort_p0 -[#grey]> Swap_a0_a1 : (ref array[i], ref array[i + 1])
        end
    end
end
@enduml
