@startuml Program
title Program
 class Program #GhostWhite {
- {const} string FILE_NAME = "pupils.csv"
---
---
- {static} void Main(string[] args)
- {static} void RunApp()
- {static} int PrintAndExecuteMenu()
- {static} Pupil[] ReadPupilsFromCsvFile(string fileName)
- {static} void WritePupilsToCsvFile(string fileName, Pupil[] pupils)
- {static} void ReadPupil(Pupil[] pupils)
- {static} void PrintPupils(Pupil[] pupils)
- {static} void SortPupilsByCatalogNumber(Pupil[] pupils)
- {static} void SortPupilsByLastName(Pupil[] pupils)
- {static} void SearchPupilsByLastName(Pupil[] pupils)
- {static} void SearchPupilsByPostalCode(Pupil[] pupils)
}
@enduml
