@startuml Program.RunApp
title Program.RunApp
participant "RunApp" as RunApp #LightYellow
participant "ReadPupilsFromCsvFile(a0)" as ReadPupilsFromCsvFile_a0 #LightGreen
participant "PrintAndExecuteMenu()" as PrintAndExecuteMenu #LightGreen
participant "ReadPupil(a0)" as ReadPupil_a0 #LightGreen
participant "SortPupilsByCatalogNumber(a0)" as SortPupilsByCatalogNumber_a0 #LightGreen
participant "SortPupilsByLastName(a0)" as SortPupilsByLastName_a0 #LightGreen
participant "PrintPupils(a0)" as PrintPupils_a0 #LightGreen
participant "SearchPupilsByLastName(a0)" as SearchPupilsByLastName_a0 #LightGreen
participant "SearchPupilsByPostalCode(a0)" as SearchPupilsByPostalCode_a0 #LightGreen
participant "WritePupilsToCsvFile(a0,a1)" as WritePupilsToCsvFile_a0_a1 #LightGreen
autonumber
RunApp -[#grey]> ReadPupilsFromCsvFile_a0 : (FILE_NAME)
ReadPupilsFromCsvFile_a0 -[#blue]-> RunApp : pupils
RunApp -[#grey]> PrintAndExecuteMenu
PrintAndExecuteMenu -[#blue]-> RunApp : choice
loop#LightCoral exit == false
    RunApp -[#grey]> ReadPupil_a0 : (pupils)
    RunApp -[#grey]> SortPupilsByCatalogNumber_a0 : (pupils)
    RunApp -[#grey]> SortPupilsByLastName_a0 : (pupils)
    RunApp -[#grey]> PrintPupils_a0 : (pupils)
    RunApp -[#grey]> SearchPupilsByLastName_a0 : (pupils)
    RunApp -[#grey]> SearchPupilsByPostalCode_a0 : (pupils)
    RunApp -[#grey]> WritePupilsToCsvFile_a0_a1 : (FILE_NAME, pupils)
    alt#LightBlue !exit
        RunApp -[#grey]> PrintAndExecuteMenu
        PrintAndExecuteMenu -[#blue]-> RunApp : choice
    end
end
@enduml
