@startuml Program.SearchPupilsByLastName
title Program.SearchPupilsByLastName
participant "SearchPupilsByLastName(Pupil[]pupils)" as SearchPupilsByLastName_p0 #LightYellow
participant "Console.Write(a0)" as Console_Write_a0 #LightGreen
participant "Console.ReadLine()" as Console_ReadLine #LightGreen
participant "pupil.LastName.Equals(a0)" as pupil_LastName_Equals_a0 #LightGreen
participant "PrintPupils(a0)" as PrintPupils_a0 #LightGreen
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
autonumber
SearchPupilsByLastName_p0 -> Console_Write_a0 : ("Familiennamen eingeben: ")
SearchPupilsByLastName_p0 -> Console_ReadLine
Console_ReadLine --> SearchPupilsByLastName_p0 : input
SearchPupilsByLastName_p0 -> pupil_LastName_Equals_a0 : (input)
pupil_LastName_Equals_a0 --> SearchPupilsByLastName_p0 : result
alt printIdx > 0
    SearchPupilsByLastName_p0 -> PrintPupils_a0 : (printList)
    else
        SearchPupilsByLastName_p0 -> Console_WriteLine_a0 : ("Keine Schüler mit diesem Familiennamen gefunden!")
end
@enduml
