@startuml Program.Main
title Program.Main
start
#Lavender:Params(string[] args);
#LightBlue:int GROWN_UP_AGE = 18
string input
int age, ageDiff;
:PrintLine("GrownUp Calculator");
:PrintLine("==================");
:PrintLine();
:Print("How old are you? ");
:input = ReadLine();
:age = Convert.ToInt32(input);
:ageDiff = age - GROWN_UP_AGE;
if (ageDiff >= 0) then (<color:green>yes)
    :PrintLine($"In approx. {ageDiff} you will be grwon-up");
  else (<color:red>no)
      :PrintLine("You are to old");
endif
if (age < 18) then (<color:green>yes)
    :PrintLine("You are under 18. ");
  else (<color:red>no)
    if (age == 18) then (<color:green>yes)
        :PrintLine("You are right now 18");
      else (<color:red>no)
        if (age > 18 || age <= 20) then (<color:green>yes)
            :PrintLine($"You are {age}");
          else (<color:red>no)
            if (age > 20 || age <= 25) then (<color:green>yes)
                :PrintLine($"You are between 21 and 25. Right now You are {age}");
              else (<color:red>no)
                  :PrintLine("You are living your life. Keep growing!!!");
            endif
        endif
    endif
endif
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
@enduml
