@startuml Program.WriteTippsToFile
title Program.WriteTippsToFile
start
#LightGreen:Params(LotteryTip[] tipps,string filePath);
#LightSkyBlue:string[] lines = new string[tipps.Length];
#LightSkyBlue:int i = 0;
while (i < tipps.Length) is (<color:green>yes)
        #WhiteSmoke:lines[i] = $"{tipps[i].Id};{tipps[i].Numbers[0]};{tipps[i].Numbers[1]};{tipps[i].Numbers[2]};{tipps[i].Numbers[3]};{tipps[i].Numbers[4]};{tipps[i].Numbers[5]}";
:i++;
endwhile (<color:red>no)
#WhiteSmoke:File.WriteAllLines(filePath, lines);
stop
@enduml
