@startuml Program.Main
title Program.Main
participant "Main" as Main #LightYellow
participant "Console.WriteLine(a0)" as Console_WriteLine_a0 #LightGreen
participant "Console.WriteLine()" as Console_WriteLine #LightGreen
participant "ReadTippsFromFile(a0)" as ReadTippsFromFile_a0 #LightGreen
participant "GetCorrectTipps(a0)" as GetCorrectTipps_a0 #LightGreen
participant "GetIncorrectTipps(a0)" as GetIncorrectTipps_a0 #LightGreen
participant "WriteTippsToFile(a0,a1)" as WriteTippsToFile_a0_a1 #LightGreen
participant "PrintTipps(a0)" as PrintTipps_a0 #LightGreen
participant "Console.ReadLine()" as Console_ReadLine #LightGreen
autonumber
Main -[#grey]> Console_WriteLine_a0 : ("LottoChecker")
Main -[#grey]> Console_WriteLine_a0 : ("============")
Main -[#grey]> Console_WriteLine
Main -[#grey]> Console_WriteLine
Main -[#grey]> ReadTippsFromFile_a0 : (FileName)
ReadTippsFromFile_a0 -[#blue]-> Main : tipps
Main -[#grey]> GetCorrectTipps_a0 : (tipps)
GetCorrectTipps_a0 -[#blue]-> Main : correctTipps
Main -[#grey]> GetIncorrectTipps_a0 : (tipps)
GetIncorrectTipps_a0 -[#blue]-> Main : incorrectTipps
Main -[#grey]> WriteTippsToFile_a0_a1 : (correctTipps, CorrectFileName)
Main -[#grey]> WriteTippsToFile_a0_a1 : (incorrectTipps, IncorrectFileName)
Main -[#grey]> Console_WriteLine_a0 : ("Incorrect Tips:")
Main -[#grey]> PrintTipps_a0 : (incorrectTipps)
Main -[#grey]> Console_WriteLine
Main -[#grey]> Console_WriteLine_a0 : ("Exit with Enter...")
Main -[#grey]> Console_ReadLine
@enduml
