@startuml Program.Main
title Program.Main
start
:PrintLine("Das große Rätsel von Dagobert!");
:PrintLine("==============================");
:PrintLine();
repeat
    :tSum = (t + 1) * t / 2;
    :qSum = q * q;
    if (tSum < qSum) then (yes)
        :t++;
      else (no)
        if (qSum < tSum) then (yes)
            :q++;
        endif
    endif
repeat while (tSum != qSum && tSum <= UPPER_RANGE) is (yes)
if (tSum == qSum) then (yes)
    :PrintLine();
    :PrintLine($"Die Lösung des Rätsels [{t},{q}]: Es sind {qSum} Dukaten!");
  else (no)
      :PrintLine();
      :PrintLine($"Es gibt keine Dreieckszahl und Quadratzahl welche im Bereich {LOWER_RANGE} - {UPPER_RANGE} gleich sind!");
endif
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
@enduml
