@startuml Program.Main
title Program.Main
start
:PrintLine(" Zahlen Statistik ");
:PrintLine("==================");
:PrintLine();
:PrintLine("Geben Sie positive ganze Zahlen ein [0..Ende]");
repeat
    :idx = idx + 1;
    :Print($"Zahl {idx}: ");
    :input = ReadLine();
    :num = Convert.ToInt32(input);
    if (num != 0) then (yes)
        :sum = sum + num;
        if (num > max) then (yes)
            :prvMax = max;
            :max = num;
          else (no)
            if (num > prvMax && num < max) then (yes)
                :prvMax = num;
            endif
        endif
        if (num < min) then (yes)
            :min = num;
        endif
        :average = sum / (double)idx;
    endif
repeat while (num != 0) is (yes)
:PrintLine();
if (idx > 1) then (yes)
    :PrintLine($"Sie haben {idx - 1} Zahlen eingegeben.");
    :PrintLine($"Die Summe der eingegebenen Zahlen ist {sum}.");
    :PrintLine($"Der maximale Wert ist {max}.");
    if (idx > 2) then (yes)
        :PrintLine($"Die zweitgrößte Zahl ist {prvMax}.");
    endif
    :PrintLine($"Der minimale Wert ist {min}.");
    :PrintLine($"Der Durchschnittswert ist {average:f}");
endif
:PrintLine();
:PrintLine("Press any key to exit: ");
:ReadKey();
stop
@enduml
